//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeEngineSession : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeEngineSession(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeEngineSession obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeEngineSession obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeEngineSession() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeEngineSession(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual string GetActivationRequest() {
    string ret = cscodeenginePINVOKE.CodeEngineSession_GetActivationRequest(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Activate(string activation_response) {
    cscodeenginePINVOKE.CodeEngineSession_Activate(swigCPtr, activation_response);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual bool IsActivated() {
    bool ret = cscodeenginePINVOKE.CodeEngineSession_IsActivated(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual CodeEngineResult Process(Image image) {
    CodeEngineResult ret = new CodeEngineResult(cscodeenginePINVOKE.CodeEngineSession_Process(swigCPtr, Image.getCPtr(image)), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual CodeEngineResult GetCurrentResult() {
    CodeEngineResult ret = new CodeEngineResult(cscodeenginePINVOKE.CodeEngineSession_GetCurrentResult(swigCPtr), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool IsResultTerminal() {
    bool ret = cscodeenginePINVOKE.CodeEngineSession_IsResultTerminal(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Reset() {
    cscodeenginePINVOKE.CodeEngineSession_Reset(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
