/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeEngineSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeEngineSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeEngineSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeEngineSession obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeEngineSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetActivationRequest() {
    return jnicodeengineJNI.CodeEngineSession_GetActivationRequest(swigCPtr, this);
  }

  public void Activate(String activation_response) {
    jnicodeengineJNI.CodeEngineSession_Activate(swigCPtr, this, activation_response);
  }

  public boolean IsActivated() {
    return jnicodeengineJNI.CodeEngineSession_IsActivated(swigCPtr, this);
  }

  public CodeEngineResult Process(Image image) {
    return new CodeEngineResult(jnicodeengineJNI.CodeEngineSession_Process(swigCPtr, this, Image.getCPtr(image), image), false);
  }

  public CodeEngineResult GetCurrentResult() {
    return new CodeEngineResult(jnicodeengineJNI.CodeEngineSession_GetCurrentResult(swigCPtr, this), false);
  }

  public boolean IsResultTerminal() {
    return jnicodeengineJNI.CodeEngineSession_IsResultTerminal(swigCPtr, this);
  }

  public void Reset() {
    jnicodeengineJNI.CodeEngineSession_Reset(swigCPtr, this);
  }

}
