/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeEngineSessionSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeEngineSessionSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeEngineSessionSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeEngineSessionSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeEngineSessionSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeEngineSessionSettings Clone() {
    long cPtr = jnicodeengineJNI.CodeEngineSessionSettings_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new CodeEngineSessionSettings(cPtr, true);
  }

  public String GetOption(String option_name) {
    return jnicodeengineJNI.CodeEngineSessionSettings_GetOption(swigCPtr, this, option_name);
  }

  public StringsMapIterator SettingsBegin() {
    return new StringsMapIterator(jnicodeengineJNI.CodeEngineSessionSettings_SettingsBegin(swigCPtr, this), true);
  }

  public StringsMapIterator SettingsEnd() {
    return new StringsMapIterator(jnicodeengineJNI.CodeEngineSessionSettings_SettingsEnd(swigCPtr, this), true);
  }

  public boolean HasOption(String option_name) {
    return jnicodeengineJNI.CodeEngineSessionSettings_HasOption(swigCPtr, this, option_name);
  }

  public void SetOption(String option_name, String option_value) {
    jnicodeengineJNI.CodeEngineSessionSettings_SetOption(swigCPtr, this, option_name, option_value);
  }

}
