/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeEngineFeedbackContainer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeEngineFeedbackContainer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeEngineFeedbackContainer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeEngineFeedbackContainer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeEngineFeedbackContainer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeEngineFeedbackContainer() {
    this(jnicodeengineJNI.new_CodeEngineFeedbackContainer__SWIG_0(), true);
  }

  public CodeEngineFeedbackContainer(CodeEngineFeedbackContainer copy) {
    this(jnicodeengineJNI.new_CodeEngineFeedbackContainer__SWIG_1(CodeEngineFeedbackContainer.getCPtr(copy), copy), true);
  }

  public int GetQuadranglesCount() {
    return jnicodeengineJNI.CodeEngineFeedbackContainer_GetQuadranglesCount(swigCPtr, this);
  }

  public boolean HasQuadrangle(String quad_name) {
    return jnicodeengineJNI.CodeEngineFeedbackContainer_HasQuadrangle(swigCPtr, this, quad_name);
  }

  public Quadrangle GetQuadrangle(String quad_name) {
    return new Quadrangle(jnicodeengineJNI.CodeEngineFeedbackContainer_GetQuadrangle(swigCPtr, this, quad_name), false);
  }

  public void SetQuadrangle(String quad_name, Quadrangle quad) {
    jnicodeengineJNI.CodeEngineFeedbackContainer_SetQuadrangle(swigCPtr, this, quad_name, Quadrangle.getCPtr(quad), quad);
  }

  public void RemoveQuadrangle(String quad_name) {
    jnicodeengineJNI.CodeEngineFeedbackContainer_RemoveQuadrangle(swigCPtr, this, quad_name);
  }

  public QuadranglesMapIterator QuadranglesBegin() {
    return new QuadranglesMapIterator(jnicodeengineJNI.CodeEngineFeedbackContainer_QuadranglesBegin(swigCPtr, this), true);
  }

  public QuadranglesMapIterator QuadranglesEnd() {
    return new QuadranglesMapIterator(jnicodeengineJNI.CodeEngineFeedbackContainer_QuadranglesEnd(swigCPtr, this), true);
  }

}
