/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeEngine {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeEngine obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static CodeEngine Create(String config_path, boolean lazy_configuration) {
    long cPtr = jnicodeengineJNI.CodeEngine_Create__SWIG_0(config_path, lazy_configuration);
    return (cPtr == 0) ? null : new CodeEngine(cPtr, true);
  }

  public static CodeEngine Create(String config_path) {
    long cPtr = jnicodeengineJNI.CodeEngine_Create__SWIG_1(config_path);
    return (cPtr == 0) ? null : new CodeEngine(cPtr, true);
  }

  public static CodeEngine Create(byte[] config_data, boolean lazy_configuration) {
    long cPtr = jnicodeengineJNI.CodeEngine_Create__SWIG_2(config_data, lazy_configuration);
    return (cPtr == 0) ? null : new CodeEngine(cPtr, true);
  }

  public static CodeEngine Create(byte[] config_data) {
    long cPtr = jnicodeengineJNI.CodeEngine_Create__SWIG_3(config_data);
    return (cPtr == 0) ? null : new CodeEngine(cPtr, true);
  }

  public static CodeEngine CreateFromEmbeddedBundle(boolean lazy_configuration) {
    long cPtr = jnicodeengineJNI.CodeEngine_CreateFromEmbeddedBundle__SWIG_0(lazy_configuration);
    return (cPtr == 0) ? null : new CodeEngine(cPtr, true);
  }

  public static CodeEngine CreateFromEmbeddedBundle() {
    long cPtr = jnicodeengineJNI.CodeEngine_CreateFromEmbeddedBundle__SWIG_1();
    return (cPtr == 0) ? null : new CodeEngine(cPtr, true);
  }

  public static String GetVersion() {
    return jnicodeengineJNI.CodeEngine_GetVersion();
  }

  public CodeEngineSessionSettings GetDefaultSessionSettings() {
    long cPtr = jnicodeengineJNI.CodeEngine_GetDefaultSessionSettings(swigCPtr, this);
    return (cPtr == 0) ? null : new CodeEngineSessionSettings(cPtr, true);
  }

  public CodeEngineSession SpawnSession(CodeEngineSessionSettings settings, String signature, CodeEngineWorkflowFeedback workflow_reporter, CodeEngineVisualizationFeedback visualization_reporter) {
    long cPtr = jnicodeengineJNI.CodeEngine_SpawnSession__SWIG_0(swigCPtr, this, CodeEngineSessionSettings.getCPtr(settings), settings, signature, CodeEngineWorkflowFeedback.getCPtr(workflow_reporter), workflow_reporter, CodeEngineVisualizationFeedback.getCPtr(visualization_reporter), visualization_reporter);
    return (cPtr == 0) ? null : new CodeEngineSession(cPtr, true);
  }

  public CodeEngineSession SpawnSession(CodeEngineSessionSettings settings, String signature, CodeEngineWorkflowFeedback workflow_reporter) {
    long cPtr = jnicodeengineJNI.CodeEngine_SpawnSession__SWIG_1(swigCPtr, this, CodeEngineSessionSettings.getCPtr(settings), settings, signature, CodeEngineWorkflowFeedback.getCPtr(workflow_reporter), workflow_reporter);
    return (cPtr == 0) ? null : new CodeEngineSession(cPtr, true);
  }

  public CodeEngineSession SpawnSession(CodeEngineSessionSettings settings, String signature) {
    long cPtr = jnicodeengineJNI.CodeEngine_SpawnSession__SWIG_2(swigCPtr, this, CodeEngineSessionSettings.getCPtr(settings), settings, signature);
    return (cPtr == 0) ? null : new CodeEngineSession(cPtr, true);
  }

  public boolean IsEngineAvailable(CodeEngineType engine_type) {
    return jnicodeengineJNI.CodeEngine_IsEngineAvailable(swigCPtr, this, engine_type.swigValue());
  }

}
