/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

public final class BarcodePreset {
  public final static BarcodePreset GS1 = new BarcodePreset("GS1", jnicodeengineJNI.BarcodePreset_GS1_get());
  public final static BarcodePreset AAMVA = new BarcodePreset("AAMVA", jnicodeengineJNI.BarcodePreset_AAMVA_get());
  public final static BarcodePreset URL = new BarcodePreset("URL", jnicodeengineJNI.BarcodePreset_URL_get());
  public final static BarcodePreset VCARD = new BarcodePreset("VCARD", jnicodeengineJNI.BarcodePreset_VCARD_get());
  public final static BarcodePreset EMAIL = new BarcodePreset("EMAIL", jnicodeengineJNI.BarcodePreset_EMAIL_get());
  public final static BarcodePreset ICALENDAR = new BarcodePreset("ICALENDAR", jnicodeengineJNI.BarcodePreset_ICALENDAR_get());
  public final static BarcodePreset PHONE = new BarcodePreset("PHONE", jnicodeengineJNI.BarcodePreset_PHONE_get());
  public final static BarcodePreset SMS = new BarcodePreset("SMS", jnicodeengineJNI.BarcodePreset_SMS_get());
  public final static BarcodePreset ISBN = new BarcodePreset("ISBN", jnicodeengineJNI.BarcodePreset_ISBN_get());
  public final static BarcodePreset WIFI = new BarcodePreset("WIFI", jnicodeengineJNI.BarcodePreset_WIFI_get());
  public final static BarcodePreset GEO = new BarcodePreset("GEO", jnicodeengineJNI.BarcodePreset_GEO_get());
  public final static BarcodePreset PAYMENT = new BarcodePreset("PAYMENT", jnicodeengineJNI.BarcodePreset_PAYMENT_get());
  public final static BarcodePreset NONE = new BarcodePreset("NONE", jnicodeengineJNI.BarcodePreset_NONE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static BarcodePreset swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + BarcodePreset.class + " with value " + swigValue);
  }

  private BarcodePreset(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private BarcodePreset(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private BarcodePreset(String swigName, BarcodePreset swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static BarcodePreset[] swigValues = { GS1, AAMVA, URL, VCARD, EMAIL, ICALENDAR, PHONE, SMS, ISBN, WIFI, GEO, PAYMENT, NONE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

