/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

public final class EngineSettingsGroup {
  public final static EngineSettingsGroup Global = new EngineSettingsGroup("Global", jnicodeengineJNI.EngineSettingsGroup_Global_get());
  public final static EngineSettingsGroup Barcode = new EngineSettingsGroup("Barcode", jnicodeengineJNI.EngineSettingsGroup_Barcode_get());
  public final static EngineSettingsGroup Card = new EngineSettingsGroup("Card", jnicodeengineJNI.EngineSettingsGroup_Card_get());
  public final static EngineSettingsGroup CodeTextLine = new EngineSettingsGroup("CodeTextLine", jnicodeengineJNI.EngineSettingsGroup_CodeTextLine_get());
  public final static EngineSettingsGroup Mrz = new EngineSettingsGroup("Mrz", jnicodeengineJNI.EngineSettingsGroup_Mrz_get());
  public final static EngineSettingsGroup PaymentDetails = new EngineSettingsGroup("PaymentDetails", jnicodeengineJNI.EngineSettingsGroup_PaymentDetails_get());
  public final static EngineSettingsGroup LicensePlate = new EngineSettingsGroup("LicensePlate", jnicodeengineJNI.EngineSettingsGroup_LicensePlate_get());
  public final static EngineSettingsGroup ContainerRecog = new EngineSettingsGroup("ContainerRecog", jnicodeengineJNI.EngineSettingsGroup_ContainerRecog_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EngineSettingsGroup swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EngineSettingsGroup.class + " with value " + swigValue);
  }

  private EngineSettingsGroup(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EngineSettingsGroup(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EngineSettingsGroup(String swigName, EngineSettingsGroup swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EngineSettingsGroup[] swigValues = { Global, Barcode, Card, CodeTextLine, Mrz, PaymentDetails, LicensePlate, ContainerRecog };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

