/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeObjectsMapIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeObjectsMapIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeObjectsMapIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeObjectsMapIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeObjectsMapIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeObjectsMapIterator(CodeObjectsMapIterator other) {
    this(jnicodeengineJNI.new_CodeObjectsMapIterator(CodeObjectsMapIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jnicodeengineJNI.CodeObjectsMapIterator_GetKey(swigCPtr, this);
  }

  public CodeObject GetValue() {
    return new CodeObject(jnicodeengineJNI.CodeObjectsMapIterator_GetValue(swigCPtr, this), false);
  }

  public boolean Equals(CodeObjectsMapIterator rvalue) {
    return jnicodeengineJNI.CodeObjectsMapIterator_Equals(swigCPtr, this, CodeObjectsMapIterator.getCPtr(rvalue), rvalue);
  }

  public void Advance() {
    jnicodeengineJNI.CodeObjectsMapIterator_Advance(swigCPtr, this);
  }

}
