//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

public enum BarcodePreset {
  GS1 = 1 << 1,
  AAMVA = 1 << 2,
  URL = 1 << 3,
  VCARD = 1 << 4,
  EMAIL = 1 << 5,
  ICALENDAR = 1 << 6,
  PHONE = 1 << 7,
  SMS = 1 << 8,
  ISBN = 1 << 9,
  WIFI = 1 << 10,
  GEO = 1 << 11,
  PAYMENT = 1 << 12,
  NONE = 1 << 13
}

}
