//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeEngineWorkflowFeedback : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeEngineWorkflowFeedback(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeEngineWorkflowFeedback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeEngineWorkflowFeedback obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeEngineWorkflowFeedback() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeEngineWorkflowFeedback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void ResultReceived(CodeEngineResult result_received) {
    cscodeenginePINVOKE.CodeEngineWorkflowFeedback_ResultReceived(swigCPtr, CodeEngineResult.getCPtr(result_received));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SessionEnded() {
    cscodeenginePINVOKE.CodeEngineWorkflowFeedback_SessionEnded(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeEngineWorkflowFeedback() : this(cscodeenginePINVOKE.new_CodeEngineWorkflowFeedback(), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("ResultReceived", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateCodeEngineWorkflowFeedback_0(SwigDirectorMethodResultReceived);
    if (SwigDerivedClassHasMethod("SessionEnded", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateCodeEngineWorkflowFeedback_1(SwigDirectorMethodSessionEnded);
    cscodeenginePINVOKE.CodeEngineWorkflowFeedback_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(CodeEngineWorkflowFeedback))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private void SwigDirectorMethodResultReceived(global::System.IntPtr result_received) {
    ResultReceived(new CodeEngineResult(result_received, false));
  }

  private void SwigDirectorMethodSessionEnded() {
    SessionEnded();
  }

  public delegate void SwigDelegateCodeEngineWorkflowFeedback_0(global::System.IntPtr result_received);
  public delegate void SwigDelegateCodeEngineWorkflowFeedback_1();

  private SwigDelegateCodeEngineWorkflowFeedback_0 swigDelegate0;
  private SwigDelegateCodeEngineWorkflowFeedback_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(CodeEngineResult) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] {  };
}

}
