/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeEngineVisualizationFeedback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeEngineVisualizationFeedback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeEngineVisualizationFeedback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeEngineVisualizationFeedback obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeEngineVisualizationFeedback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jnicodeengineJNI.CodeEngineVisualizationFeedback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jnicodeengineJNI.CodeEngineVisualizationFeedback_change_ownership(this, swigCPtr, true);
  }

  public void FeedbackReceived(CodeEngineFeedbackContainer feedback_container) {
    jnicodeengineJNI.CodeEngineVisualizationFeedback_FeedbackReceived(swigCPtr, this, CodeEngineFeedbackContainer.getCPtr(feedback_container), feedback_container);
  }

  public CodeEngineVisualizationFeedback() {
    this(jnicodeengineJNI.new_CodeEngineVisualizationFeedback(), true);
    jnicodeengineJNI.CodeEngineVisualizationFeedback_director_connect(this, swigCPtr, true, true);
  }

}
