/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

public final class CodeObjectType {
  public final static CodeObjectType CodeObject_LinearBarcode = new CodeObjectType("CodeObject_LinearBarcode", jnicodeengineJNI.CodeObject_LinearBarcode_get());
  public final static CodeObjectType CodeObject_MatrixBarcode = new CodeObjectType("CodeObject_MatrixBarcode", jnicodeengineJNI.CodeObject_MatrixBarcode_get());
  public final static CodeObjectType CodeObject_CodeTextLine = new CodeObjectType("CodeObject_CodeTextLine", jnicodeengineJNI.CodeObject_CodeTextLine_get());
  public final static CodeObjectType CodeObject_MRZ = new CodeObjectType("CodeObject_MRZ", jnicodeengineJNI.CodeObject_MRZ_get());
  public final static CodeObjectType CodeObject_BankCard = new CodeObjectType("CodeObject_BankCard", jnicodeengineJNI.CodeObject_BankCard_get());
  public final static CodeObjectType CodeObject_PaymentDetails = new CodeObjectType("CodeObject_PaymentDetails", jnicodeengineJNI.CodeObject_PaymentDetails_get());
  public final static CodeObjectType CodeObject_Face = new CodeObjectType("CodeObject_Face", jnicodeengineJNI.CodeObject_Face_get());
  public final static CodeObjectType CodeObject_Container = new CodeObjectType("CodeObject_Container", jnicodeengineJNI.CodeObject_Container_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CodeObjectType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CodeObjectType.class + " with value " + swigValue);
  }

  private CodeObjectType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CodeObjectType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CodeObjectType(String swigName, CodeObjectType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CodeObjectType[] swigValues = { CodeObject_LinearBarcode, CodeObject_MatrixBarcode, CodeObject_CodeTextLine, CodeObject_MRZ, CodeObject_BankCard, CodeObject_PaymentDetails, CodeObject_Face, CodeObject_Container };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

