/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeField() {
    this(jnicodeengineJNI.new_CodeField__SWIG_0(), true);
  }

  public CodeField(String name, ByteString byte_string, boolean is_accepted, float confidence) {
    this(jnicodeengineJNI.new_CodeField__SWIG_1(name, ByteString.getCPtr(byte_string), byte_string, is_accepted, confidence), true);
  }

  public CodeField(String name, ByteString byte_string, boolean is_accepted) {
    this(jnicodeengineJNI.new_CodeField__SWIG_2(name, ByteString.getCPtr(byte_string), byte_string, is_accepted), true);
  }

  public CodeField(String name, ByteString byte_string) {
    this(jnicodeengineJNI.new_CodeField__SWIG_3(name, ByteString.getCPtr(byte_string), byte_string), true);
  }

  public CodeField(String name, OcrString ocr_string, boolean is_accepted, float confidence) {
    this(jnicodeengineJNI.new_CodeField__SWIG_4(name, OcrString.getCPtr(ocr_string), ocr_string, is_accepted, confidence), true);
  }

  public CodeField(String name, OcrString ocr_string, boolean is_accepted) {
    this(jnicodeengineJNI.new_CodeField__SWIG_5(name, OcrString.getCPtr(ocr_string), ocr_string, is_accepted), true);
  }

  public CodeField(String name, OcrString ocr_string) {
    this(jnicodeengineJNI.new_CodeField__SWIG_6(name, OcrString.getCPtr(ocr_string), ocr_string), true);
  }

  public CodeField(CodeField copy) {
    this(jnicodeengineJNI.new_CodeField__SWIG_7(CodeField.getCPtr(copy), copy), true);
  }

  public String Name() {
    return jnicodeengineJNI.CodeField_Name(swigCPtr, this);
  }

  public void SetName(String name) {
    jnicodeengineJNI.CodeField_SetName(swigCPtr, this, name);
  }

  public boolean IsAccepted() {
    return jnicodeengineJNI.CodeField_IsAccepted(swigCPtr, this);
  }

  public void SetIsAccepted(boolean is_accepted) {
    jnicodeengineJNI.CodeField_SetIsAccepted(swigCPtr, this, is_accepted);
  }

  public double GetConfidence() {
    return jnicodeengineJNI.CodeField_GetConfidence(swigCPtr, this);
  }

  public void SetConfidence(float confidence) {
    jnicodeengineJNI.CodeField_SetConfidence(swigCPtr, this, confidence);
  }

  public boolean IsTerminal() {
    return jnicodeengineJNI.CodeField_IsTerminal(swigCPtr, this);
  }

  public void SetIsTerminal(boolean is_terminal) {
    jnicodeengineJNI.CodeField_SetIsTerminal(swigCPtr, this, is_terminal);
  }

  public boolean HasBinaryRepresentation() {
    return jnicodeengineJNI.CodeField_HasBinaryRepresentation(swigCPtr, this);
  }

  public ByteString GetBinaryRepresentation() {
    return new ByteString(jnicodeengineJNI.CodeField_GetBinaryRepresentation(swigCPtr, this), false);
  }

  public void SetBinaryRepresentation(ByteString byte_string) {
    jnicodeengineJNI.CodeField_SetBinaryRepresentation(swigCPtr, this, ByteString.getCPtr(byte_string), byte_string);
  }

  public boolean HasOcrStringRepresentation() {
    return jnicodeengineJNI.CodeField_HasOcrStringRepresentation(swigCPtr, this);
  }

  public OcrString GetOcrString() {
    return new OcrString(jnicodeengineJNI.CodeField_GetOcrString(swigCPtr, this), false);
  }

  public void SetOcrStringRepresentation(OcrString ocr_string) {
    jnicodeengineJNI.CodeField_SetOcrStringRepresentation(swigCPtr, this, OcrString.getCPtr(ocr_string), ocr_string);
  }

}
