# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pycodeengine
else:
    import _pycodeengine

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SerializationParameters(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_SerializationParameters

    def __init__(self, *args):
        _pycodeengine.SerializationParameters_swiginit(self, _pycodeengine.new_SerializationParameters(*args))

    def HasIgnoredObjectType(self, object_type):
        return _pycodeengine.SerializationParameters_HasIgnoredObjectType(self, object_type)

    def AddIgnoredObjectType(self, object_type):
        return _pycodeengine.SerializationParameters_AddIgnoredObjectType(self, object_type)

    def RemoveIgnoredObjectType(self, object_type):
        return _pycodeengine.SerializationParameters_RemoveIgnoredObjectType(self, object_type)

    def IgnoredObjectTypesBegin(self):
        return _pycodeengine.SerializationParameters_IgnoredObjectTypesBegin(self)

    def IgnoredObjectTypesEnd(self):
        return _pycodeengine.SerializationParameters_IgnoredObjectTypesEnd(self)

    def HasIgnoredKey(self, key):
        return _pycodeengine.SerializationParameters_HasIgnoredKey(self, key)

    def AddIgnoredKey(self, key):
        return _pycodeengine.SerializationParameters_AddIgnoredKey(self, key)

    def RemoveIgnoredKey(self, key):
        return _pycodeengine.SerializationParameters_RemoveIgnoredKey(self, key)

    def IgnoredKeysBegin(self):
        return _pycodeengine.SerializationParameters_IgnoredKeysBegin(self)

    def IgnoredKeysEnd(self):
        return _pycodeengine.SerializationParameters_IgnoredKeysEnd(self)

# Register SerializationParameters in _pycodeengine:
_pycodeengine.SerializationParameters_swigregister(SerializationParameters)
class Serializer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_Serializer

    def Reset(self):
        return _pycodeengine.Serializer_Reset(self)

    def GetCStr(self):
        return _pycodeengine.Serializer_GetCStr(self)

    def SerializerType(self):
        return _pycodeengine.Serializer_SerializerType(self)

    @staticmethod
    def CreateJSONSerializer(params):
        return _pycodeengine.Serializer_CreateJSONSerializer(params)

# Register Serializer in _pycodeengine:
_pycodeengine.Serializer_swigregister(Serializer)
class Rectangle(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.Rectangle_swiginit(self, _pycodeengine.new_Rectangle(*args))

    def Serialize(self, serializer):
        return _pycodeengine.Rectangle_Serialize(self, serializer)
    x = property(_pycodeengine.Rectangle_x_get, _pycodeengine.Rectangle_x_set)
    y = property(_pycodeengine.Rectangle_y_get, _pycodeengine.Rectangle_y_set)
    width = property(_pycodeengine.Rectangle_width_get, _pycodeengine.Rectangle_width_set)
    height = property(_pycodeengine.Rectangle_height_get, _pycodeengine.Rectangle_height_set)
    __swig_destroy__ = _pycodeengine.delete_Rectangle

# Register Rectangle in _pycodeengine:
_pycodeengine.Rectangle_swigregister(Rectangle)
class Point(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.Point_swiginit(self, _pycodeengine.new_Point(*args))

    def Serialize(self, serializer):
        return _pycodeengine.Point_Serialize(self, serializer)
    x = property(_pycodeengine.Point_x_get, _pycodeengine.Point_x_set)
    y = property(_pycodeengine.Point_y_get, _pycodeengine.Point_y_set)
    __swig_destroy__ = _pycodeengine.delete_Point

# Register Point in _pycodeengine:
_pycodeengine.Point_swigregister(Point)
class Size(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.Size_swiginit(self, _pycodeengine.new_Size(*args))

    def Serialize(self, serializer):
        return _pycodeengine.Size_Serialize(self, serializer)
    width = property(_pycodeengine.Size_width_get, _pycodeengine.Size_width_set)
    height = property(_pycodeengine.Size_height_get, _pycodeengine.Size_height_set)
    __swig_destroy__ = _pycodeengine.delete_Size

# Register Size in _pycodeengine:
_pycodeengine.Size_swigregister(Size)
class Quadrangle(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.Quadrangle_swiginit(self, _pycodeengine.new_Quadrangle(*args))

    def GetPoint(self, index):
        return _pycodeengine.Quadrangle_GetPoint(self, index)

    def GetMutablePoint(self, index):
        return _pycodeengine.Quadrangle_GetMutablePoint(self, index)

    def SetPoint(self, index, p):
        return _pycodeengine.Quadrangle_SetPoint(self, index, p)

    def GetBoundingRectangle(self):
        return _pycodeengine.Quadrangle_GetBoundingRectangle(self)

    def Serialize(self, serializer):
        return _pycodeengine.Quadrangle_Serialize(self, serializer)
    __swig_destroy__ = _pycodeengine.delete_Quadrangle

# Register Quadrangle in _pycodeengine:
_pycodeengine.Quadrangle_swigregister(Quadrangle)
class QuadranglesMapIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, other):
        _pycodeengine.QuadranglesMapIterator_swiginit(self, _pycodeengine.new_QuadranglesMapIterator(other))
    __swig_destroy__ = _pycodeengine.delete_QuadranglesMapIterator

    def GetKey(self):
        return _pycodeengine.QuadranglesMapIterator_GetKey(self)

    def GetValue(self):
        return _pycodeengine.QuadranglesMapIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.QuadranglesMapIterator_Equals(self, rvalue)

    def __eq__(self, rvalue):
        return _pycodeengine.QuadranglesMapIterator___eq__(self, rvalue)

    def __ne__(self, rvalue):
        return _pycodeengine.QuadranglesMapIterator___ne__(self, rvalue)

    def Advance(self):
        return _pycodeengine.QuadranglesMapIterator_Advance(self)

# Register QuadranglesMapIterator in _pycodeengine:
_pycodeengine.QuadranglesMapIterator_swigregister(QuadranglesMapIterator)
class RectanglesVectorIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, other):
        _pycodeengine.RectanglesVectorIterator_swiginit(self, _pycodeengine.new_RectanglesVectorIterator(other))
    __swig_destroy__ = _pycodeengine.delete_RectanglesVectorIterator

    def GetValue(self):
        return _pycodeengine.RectanglesVectorIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.RectanglesVectorIterator_Equals(self, rvalue)

    def __eq__(self, rvalue):
        return _pycodeengine.RectanglesVectorIterator___eq__(self, rvalue)

    def __ne__(self, rvalue):
        return _pycodeengine.RectanglesVectorIterator___ne__(self, rvalue)

    def Advance(self):
        return _pycodeengine.RectanglesVectorIterator_Advance(self)

# Register RectanglesVectorIterator in _pycodeengine:
_pycodeengine.RectanglesVectorIterator_swigregister(RectanglesVectorIterator)
class Polygon(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.Polygon_swiginit(self, _pycodeengine.new_Polygon(*args))
    __swig_destroy__ = _pycodeengine.delete_Polygon

    def GetPointsCount(self):
        return _pycodeengine.Polygon_GetPointsCount(self)

    def GetPoints(self):
        return _pycodeengine.Polygon_GetPoints(self)

    def GetPoint(self, index):
        return _pycodeengine.Polygon_GetPoint(self, index)

    def GetMutablePoint(self, index):
        return _pycodeengine.Polygon_GetMutablePoint(self, index)

    def SetPoint(self, index, p):
        return _pycodeengine.Polygon_SetPoint(self, index, p)

    def Resize(self, size):
        return _pycodeengine.Polygon_Resize(self, size)

    def GetBoundingRectangle(self):
        return _pycodeengine.Polygon_GetBoundingRectangle(self)

    def Serialize(self, serializer):
        return _pycodeengine.Polygon_Serialize(self, serializer)

# Register Polygon in _pycodeengine:
_pycodeengine.Polygon_swigregister(Polygon)
class ProjectiveTransform(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def CanCreate(*args):
        return _pycodeengine.ProjectiveTransform_CanCreate(*args)

    @staticmethod
    def Create(*args):
        return _pycodeengine.ProjectiveTransform_Create(*args)
    __swig_destroy__ = _pycodeengine.delete_ProjectiveTransform

    def Clone(self):
        return _pycodeengine.ProjectiveTransform_Clone(self)

    def TransformPoint(self, p):
        return _pycodeengine.ProjectiveTransform_TransformPoint(self, p)

    def TransformQuad(self, q):
        return _pycodeengine.ProjectiveTransform_TransformQuad(self, q)

    def TransformPolygon(self, poly):
        return _pycodeengine.ProjectiveTransform_TransformPolygon(self, poly)

    def IsInvertable(self):
        return _pycodeengine.ProjectiveTransform_IsInvertable(self)

    def Invert(self):
        return _pycodeengine.ProjectiveTransform_Invert(self)

    def CloneInverted(self):
        return _pycodeengine.ProjectiveTransform_CloneInverted(self)

    def Serialize(self, serializer):
        return _pycodeengine.ProjectiveTransform_Serialize(self, serializer)

# Register ProjectiveTransform in _pycodeengine:
_pycodeengine.ProjectiveTransform_swigregister(ProjectiveTransform)
class MutableString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.MutableString_swiginit(self, _pycodeengine.new_MutableString(*args))
    __swig_destroy__ = _pycodeengine.delete_MutableString

    def __iadd__(self, other):
        return _pycodeengine.MutableString___iadd__(self, other)

    def __add__(self, other):
        return _pycodeengine.MutableString___add__(self, other)

    def GetCStr(self):
        return _pycodeengine.MutableString_GetCStr(self)

    def GetLength(self):
        return _pycodeengine.MutableString_GetLength(self)

    def Serialize(self, serializer):
        return _pycodeengine.MutableString_Serialize(self, serializer)

# Register MutableString in _pycodeengine:
_pycodeengine.MutableString_swigregister(MutableString)
class OcrCharVariant(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.OcrCharVariant_swiginit(self, _pycodeengine.new_OcrCharVariant(*args))
    __swig_destroy__ = _pycodeengine.delete_OcrCharVariant

    def GetCharacter(self):
        return _pycodeengine.OcrCharVariant_GetCharacter(self)

    def SetCharacter(self, *args):
        return _pycodeengine.OcrCharVariant_SetCharacter(self, *args)

    def GetConfidence(self):
        return _pycodeengine.OcrCharVariant_GetConfidence(self)

    def SetConfidence(self, confidence):
        return _pycodeengine.OcrCharVariant_SetConfidence(self, confidence)

    def GetInternalScore(self):
        return _pycodeengine.OcrCharVariant_GetInternalScore(self)

    def SetInternalScore(self, internal_score):
        return _pycodeengine.OcrCharVariant_SetInternalScore(self, internal_score)

    def Serialize(self, serializer):
        return _pycodeengine.OcrCharVariant_Serialize(self, serializer)

# Register OcrCharVariant in _pycodeengine:
_pycodeengine.OcrCharVariant_swigregister(OcrCharVariant)
class OcrChar(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.OcrChar_swiginit(self, _pycodeengine.new_OcrChar(*args))
    __swig_destroy__ = _pycodeengine.delete_OcrChar

    def GetVariantsCount(self):
        return _pycodeengine.OcrChar_GetVariantsCount(self)

    def GetVariants(self):
        return _pycodeengine.OcrChar_GetVariants(self)

    def GetVariant(self, index):
        return _pycodeengine.OcrChar_GetVariant(self, index)

    def GetMutableVariant(self, index):
        return _pycodeengine.OcrChar_GetMutableVariant(self, index)

    def SetVariant(self, index, v):
        return _pycodeengine.OcrChar_SetVariant(self, index, v)

    def Resize(self, size):
        return _pycodeengine.OcrChar_Resize(self, size)

    def GetIsHighlighted(self):
        return _pycodeengine.OcrChar_GetIsHighlighted(self)

    def SetIsHighlighted(self, is_highlighted):
        return _pycodeengine.OcrChar_SetIsHighlighted(self, is_highlighted)

    def GetQuadrangle(self):
        return _pycodeengine.OcrChar_GetQuadrangle(self)

    def GetMutableQuadrangle(self):
        return _pycodeengine.OcrChar_GetMutableQuadrangle(self)

    def SetQuadrangle(self, quad):
        return _pycodeengine.OcrChar_SetQuadrangle(self, quad)

    def SortVariants(self):
        return _pycodeengine.OcrChar_SortVariants(self)

    def GetFirstVariant(self):
        return _pycodeengine.OcrChar_GetFirstVariant(self)

    def Serialize(self, serializer):
        return _pycodeengine.OcrChar_Serialize(self, serializer)

# Register OcrChar in _pycodeengine:
_pycodeengine.OcrChar_swigregister(OcrChar)
class OcrString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.OcrString_swiginit(self, _pycodeengine.new_OcrString(*args))
    __swig_destroy__ = _pycodeengine.delete_OcrString

    def GetCharsCount(self):
        return _pycodeengine.OcrString_GetCharsCount(self)

    def GetChars(self):
        return _pycodeengine.OcrString_GetChars(self)

    def GetChar(self, index):
        return _pycodeengine.OcrString_GetChar(self, index)

    def GetMutableChar(self, index):
        return _pycodeengine.OcrString_GetMutableChar(self, index)

    def SetChar(self, index, chr):
        return _pycodeengine.OcrString_SetChar(self, index, chr)

    def AppendChar(self, chr):
        return _pycodeengine.OcrString_AppendChar(self, chr)

    def AppendString(self, str):
        return _pycodeengine.OcrString_AppendString(self, str)

    def Resize(self, size):
        return _pycodeengine.OcrString_Resize(self, size)

    def GetQuadrangleByIndex(self, idx):
        return _pycodeengine.OcrString_GetQuadrangleByIndex(self, idx)

    def GetBestVariantConfidenceByIndex(self, idx):
        return _pycodeengine.OcrString_GetBestVariantConfidenceByIndex(self, idx)

    def SortVariants(self):
        return _pycodeengine.OcrString_SortVariants(self)

    def GetFirstString(self):
        return _pycodeengine.OcrString_GetFirstString(self)

    def UnpackChars(self):
        return _pycodeengine.OcrString_UnpackChars(self)

    def RepackChars(self):
        return _pycodeengine.OcrString_RepackChars(self)

    def Serialize(self, serializer):
        return _pycodeengine.OcrString_Serialize(self, serializer)

# Register OcrString in _pycodeengine:
_pycodeengine.OcrString_swigregister(OcrString)
class ByteString(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_ByteString

    def __init__(self, *args):
        _pycodeengine.ByteString_swiginit(self, _pycodeengine.new_ByteString(*args))

    def swap(self, other):
        return _pycodeengine.ByteString_swap(self, other)

    def GetLength(self):
        return _pycodeengine.ByteString_GetLength(self)

    def GetRequiredBase64BufferLength(self):
        return _pycodeengine.ByteString_GetRequiredBase64BufferLength(self)

    def CopyBase64ToBuffer(self, out_buffer, buffer_length):
        return _pycodeengine.ByteString_CopyBase64ToBuffer(self, out_buffer, buffer_length)

    def GetBase64String(self):
        return _pycodeengine.ByteString_GetBase64String(self)

    def GetRequiredHexBufferLength(self):
        return _pycodeengine.ByteString_GetRequiredHexBufferLength(self)

    def CopyHexToBuffer(self, out_buffer, buffer_length):
        return _pycodeengine.ByteString_CopyHexToBuffer(self, out_buffer, buffer_length)

    def GetHexString(self):
        return _pycodeengine.ByteString_GetHexString(self)

# Register ByteString in _pycodeengine:
_pycodeengine.ByteString_swigregister(ByteString)
class ImagesMapIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, other):
        _pycodeengine.ImagesMapIterator_swiginit(self, _pycodeengine.new_ImagesMapIterator(other))
    __swig_destroy__ = _pycodeengine.delete_ImagesMapIterator

    def GetKey(self):
        return _pycodeengine.ImagesMapIterator_GetKey(self)

    def GetValue(self):
        return _pycodeengine.ImagesMapIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.ImagesMapIterator_Equals(self, rvalue)

    def __eq__(self, rvalue):
        return _pycodeengine.ImagesMapIterator___eq__(self, rvalue)

    def __ne__(self, rvalue):
        return _pycodeengine.ImagesMapIterator___ne__(self, rvalue)

    def Advance(self):
        return _pycodeengine.ImagesMapIterator_Advance(self)

# Register ImagesMapIterator in _pycodeengine:
_pycodeengine.ImagesMapIterator_swigregister(ImagesMapIterator)
IPF_G = _pycodeengine.IPF_G
IPF_GA = _pycodeengine.IPF_GA
IPF_AG = _pycodeengine.IPF_AG
IPF_RGB = _pycodeengine.IPF_RGB
IPF_BGR = _pycodeengine.IPF_BGR
IPF_BGRA = _pycodeengine.IPF_BGRA
IPF_ARGB = _pycodeengine.IPF_ARGB
IPF_RGBA = _pycodeengine.IPF_RGBA
YUVTYPE_UNDEFINED = _pycodeengine.YUVTYPE_UNDEFINED
YUVTYPE_NV21 = _pycodeengine.YUVTYPE_NV21
YUVTYPE_420_888 = _pycodeengine.YUVTYPE_420_888
class YUVDimensions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.YUVDimensions_swiginit(self, _pycodeengine.new_YUVDimensions(*args))
    yPlanePixelStride = property(_pycodeengine.YUVDimensions_yPlanePixelStride_get, _pycodeengine.YUVDimensions_yPlanePixelStride_set)
    yPlaneRowStride = property(_pycodeengine.YUVDimensions_yPlaneRowStride_get, _pycodeengine.YUVDimensions_yPlaneRowStride_set)
    uPlanePixelStride = property(_pycodeengine.YUVDimensions_uPlanePixelStride_get, _pycodeengine.YUVDimensions_uPlanePixelStride_set)
    uPlaneRowStride = property(_pycodeengine.YUVDimensions_uPlaneRowStride_get, _pycodeengine.YUVDimensions_uPlaneRowStride_set)
    vPlanePixelStride = property(_pycodeengine.YUVDimensions_vPlanePixelStride_get, _pycodeengine.YUVDimensions_vPlanePixelStride_set)
    vPlaneRowStride = property(_pycodeengine.YUVDimensions_vPlaneRowStride_get, _pycodeengine.YUVDimensions_vPlaneRowStride_set)
    width = property(_pycodeengine.YUVDimensions_width_get, _pycodeengine.YUVDimensions_width_set)
    height = property(_pycodeengine.YUVDimensions_height_get, _pycodeengine.YUVDimensions_height_set)
    type = property(_pycodeengine.YUVDimensions_type_get, _pycodeengine.YUVDimensions_type_set)
    __swig_destroy__ = _pycodeengine.delete_YUVDimensions

# Register YUVDimensions in _pycodeengine:
_pycodeengine.YUVDimensions_swigregister(YUVDimensions)
class Image(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def GetNumberOfPages(image_filename):
        return _pycodeengine.Image_GetNumberOfPages(image_filename)

    @staticmethod
    def GetImagePageName(image_filename, page_number):
        return _pycodeengine.Image_GetImagePageName(image_filename, page_number)

    @staticmethod
    def CreateEmpty():
        return _pycodeengine.Image_CreateEmpty()

    @staticmethod
    def FromFile(*args):
        return _pycodeengine.Image_FromFile(*args)

    @staticmethod
    def FromFileBuffer(*args):
        return _pycodeengine.Image_FromFileBuffer(*args)

    @staticmethod
    def FromBuffer(raw_data, width, height, stride, channels):
        return _pycodeengine.Image_FromBuffer(raw_data, width, height, stride, channels)

    @staticmethod
    def FromBufferExtended(raw_data, width, height, stride, pixel_format, bytes_per_channel):
        return _pycodeengine.Image_FromBufferExtended(raw_data, width, height, stride, pixel_format, bytes_per_channel)

    @staticmethod
    def FromYUVBuffer(yuv_data, width, height):
        return _pycodeengine.Image_FromYUVBuffer(yuv_data, width, height)

    @staticmethod
    def FromYUV(y_plane, u_plane, v_plane, dimensions):
        return _pycodeengine.Image_FromYUV(y_plane, u_plane, v_plane, dimensions)

    @staticmethod
    def FromBase64Buffer(*args):
        return _pycodeengine.Image_FromBase64Buffer(*args)
    __swig_destroy__ = _pycodeengine.delete_Image

    def GetNumberOfLayers(self):
        return _pycodeengine.Image_GetNumberOfLayers(self)

    def GetLayer(self, name):
        return _pycodeengine.Image_GetLayer(self, name)

    def GetLayerPtr(self, name):
        return _pycodeengine.Image_GetLayerPtr(self, name)

    def LayersBegin(self):
        return _pycodeengine.Image_LayersBegin(self)

    def LayersEnd(self):
        return _pycodeengine.Image_LayersEnd(self)

    def HasLayer(self, name):
        return _pycodeengine.Image_HasLayer(self, name)

    def HasLayers(self):
        return _pycodeengine.Image_HasLayers(self)

    def RemoveLayer(self, name):
        return _pycodeengine.Image_RemoveLayer(self, name)

    def RemoveLayers(self):
        return _pycodeengine.Image_RemoveLayers(self)

    def SetLayer(self, name, image):
        return _pycodeengine.Image_SetLayer(self, name, image)

    def SetLayerWithOwnership(self, name, image):
        return _pycodeengine.Image_SetLayerWithOwnership(self, name, image)

    def CloneDeep(self):
        return _pycodeengine.Image_CloneDeep(self)

    def CloneShallow(self):
        return _pycodeengine.Image_CloneShallow(self)

    def Clear(self):
        return _pycodeengine.Image_Clear(self)

    def GetRequiredBufferLength(self):
        return _pycodeengine.Image_GetRequiredBufferLength(self)

    def CopyToBuffer(self, buffer):
        return _pycodeengine.Image_CopyToBuffer(self, buffer)

    def Save(self, image_filename):
        return _pycodeengine.Image_Save(self, image_filename)

    def GetRequiredBase64BufferLength(self):
        return _pycodeengine.Image_GetRequiredBase64BufferLength(self)

    def CopyBase64ToBuffer(self, out_buffer, buffer_length):
        return _pycodeengine.Image_CopyBase64ToBuffer(self, out_buffer, buffer_length)

    def GetBase64String(self):
        return _pycodeengine.Image_GetBase64String(self)

    def EstimateFocusScore(self, quantile=0.95):
        return _pycodeengine.Image_EstimateFocusScore(self, quantile)

    def Resize(self, new_size):
        return _pycodeengine.Image_Resize(self, new_size)

    def CloneResized(self, new_size):
        return _pycodeengine.Image_CloneResized(self, new_size)

    def Crop(self, *args):
        return _pycodeengine.Image_Crop(self, *args)

    def CloneCropped(self, *args):
        return _pycodeengine.Image_CloneCropped(self, *args)

    def CloneCroppedShallow(self, rect):
        return _pycodeengine.Image_CloneCroppedShallow(self, rect)

    def Mask(self, *args):
        return _pycodeengine.Image_Mask(self, *args)

    def CloneMasked(self, *args):
        return _pycodeengine.Image_CloneMasked(self, *args)

    def Fill(self, *args):
        return _pycodeengine.Image_Fill(self, *args)

    def CloneFilled(self, *args):
        return _pycodeengine.Image_CloneFilled(self, *args)

    def FlipVertical(self):
        return _pycodeengine.Image_FlipVertical(self)

    def CloneFlippedVertical(self):
        return _pycodeengine.Image_CloneFlippedVertical(self)

    def FlipHorizontal(self):
        return _pycodeengine.Image_FlipHorizontal(self)

    def CloneFlippedHorizontal(self):
        return _pycodeengine.Image_CloneFlippedHorizontal(self)

    def Rotate90(self, times):
        return _pycodeengine.Image_Rotate90(self, times)

    def CloneRotated90(self, times):
        return _pycodeengine.Image_CloneRotated90(self, times)

    def AverageChannels(self):
        return _pycodeengine.Image_AverageChannels(self)

    def CloneAveragedChannels(self):
        return _pycodeengine.Image_CloneAveragedChannels(self)

    def Invert(self):
        return _pycodeengine.Image_Invert(self)

    def CloneInverted(self):
        return _pycodeengine.Image_CloneInverted(self)

    def GetWidth(self):
        return _pycodeengine.Image_GetWidth(self)

    def GetHeight(self):
        return _pycodeengine.Image_GetHeight(self)

    def GetSize(self):
        return _pycodeengine.Image_GetSize(self)

    def GetStride(self):
        return _pycodeengine.Image_GetStride(self)

    def GetChannels(self):
        return _pycodeengine.Image_GetChannels(self)

    def IsMemoryOwner(self):
        return _pycodeengine.Image_IsMemoryOwner(self)

    def ForceMemoryOwner(self):
        return _pycodeengine.Image_ForceMemoryOwner(self)

    def Serialize(self, serializer):
        return _pycodeengine.Image_Serialize(self, serializer)

# Register Image in _pycodeengine:
_pycodeengine.Image_swigregister(Image)
class StringsVectorIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, other):
        _pycodeengine.StringsVectorIterator_swiginit(self, _pycodeengine.new_StringsVectorIterator(other))
    __swig_destroy__ = _pycodeengine.delete_StringsVectorIterator

    def GetValue(self):
        return _pycodeengine.StringsVectorIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.StringsVectorIterator_Equals(self, rvalue)

    def __eq__(self, rvalue):
        return _pycodeengine.StringsVectorIterator___eq__(self, rvalue)

    def __ne__(self, rvalue):
        return _pycodeengine.StringsVectorIterator___ne__(self, rvalue)

    def Advance(self):
        return _pycodeengine.StringsVectorIterator_Advance(self)

# Register StringsVectorIterator in _pycodeengine:
_pycodeengine.StringsVectorIterator_swigregister(StringsVectorIterator)
class StringsSetIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, other):
        _pycodeengine.StringsSetIterator_swiginit(self, _pycodeengine.new_StringsSetIterator(other))
    __swig_destroy__ = _pycodeengine.delete_StringsSetIterator

    def GetValue(self):
        return _pycodeengine.StringsSetIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.StringsSetIterator_Equals(self, rvalue)

    def __eq__(self, rvalue):
        return _pycodeengine.StringsSetIterator___eq__(self, rvalue)

    def __ne__(self, rvalue):
        return _pycodeengine.StringsSetIterator___ne__(self, rvalue)

    def Advance(self):
        return _pycodeengine.StringsSetIterator_Advance(self)

# Register StringsSetIterator in _pycodeengine:
_pycodeengine.StringsSetIterator_swigregister(StringsSetIterator)
class StringsMapIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, other):
        _pycodeengine.StringsMapIterator_swiginit(self, _pycodeengine.new_StringsMapIterator(other))
    __swig_destroy__ = _pycodeengine.delete_StringsMapIterator

    def GetKey(self):
        return _pycodeengine.StringsMapIterator_GetKey(self)

    def GetValue(self):
        return _pycodeengine.StringsMapIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.StringsMapIterator_Equals(self, rvalue)

    def __eq__(self, rvalue):
        return _pycodeengine.StringsMapIterator___eq__(self, rvalue)

    def __ne__(self, rvalue):
        return _pycodeengine.StringsMapIterator___ne__(self, rvalue)

    def Advance(self):
        return _pycodeengine.StringsMapIterator_Advance(self)

# Register StringsMapIterator in _pycodeengine:
_pycodeengine.StringsMapIterator_swigregister(StringsMapIterator)
class StringsSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_StringsSet

    def GetStringsCount(self):
        return _pycodeengine.StringsSet_GetStringsCount(self)

    def HasString(self, string):
        return _pycodeengine.StringsSet_HasString(self, string)

    def StringsBegin(self):
        return _pycodeengine.StringsSet_StringsBegin(self)

    def StringsEnd(self):
        return _pycodeengine.StringsSet_StringsEnd(self)

# Register StringsSet in _pycodeengine:
_pycodeengine.StringsSet_swigregister(StringsSet)
class CodeEngineSessionSettings(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeEngineSessionSettings

    def Clone(self):
        return _pycodeengine.CodeEngineSessionSettings_Clone(self)

    def GetOption(self, option_name):
        return _pycodeengine.CodeEngineSessionSettings_GetOption(self, option_name)

    def SettingsBegin(self):
        return _pycodeengine.CodeEngineSessionSettings_SettingsBegin(self)

    def SettingsEnd(self):
        return _pycodeengine.CodeEngineSessionSettings_SettingsEnd(self)

    def HasOption(self, option_name):
        return _pycodeengine.CodeEngineSessionSettings_HasOption(self, option_name)

    def SetOption(self, option_name, option_value):
        return _pycodeengine.CodeEngineSessionSettings_SetOption(self, option_name, option_value)

# Register CodeEngineSessionSettings in _pycodeengine:
_pycodeengine.CodeEngineSessionSettings_swigregister(CodeEngineSessionSettings)
class CodeField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeField

    def __init__(self, *args):
        _pycodeengine.CodeField_swiginit(self, _pycodeengine.new_CodeField(*args))

    def __eq__(self, other):
        return _pycodeengine.CodeField___eq__(self, other)

    def Name(self):
        return _pycodeengine.CodeField_Name(self)

    def SetName(self, name):
        return _pycodeengine.CodeField_SetName(self, name)

    def IsAccepted(self):
        return _pycodeengine.CodeField_IsAccepted(self)

    def SetIsAccepted(self, is_accepted):
        return _pycodeengine.CodeField_SetIsAccepted(self, is_accepted)

    def GetConfidence(self):
        return _pycodeengine.CodeField_GetConfidence(self)

    def SetConfidence(self, confidence):
        return _pycodeengine.CodeField_SetConfidence(self, confidence)

    def IsTerminal(self):
        return _pycodeengine.CodeField_IsTerminal(self)

    def SetIsTerminal(self, is_terminal):
        return _pycodeengine.CodeField_SetIsTerminal(self, is_terminal)

    def HasBinaryRepresentation(self):
        return _pycodeengine.CodeField_HasBinaryRepresentation(self)

    def GetBinaryRepresentation(self):
        return _pycodeengine.CodeField_GetBinaryRepresentation(self)

    def SetBinaryRepresentation(self, byte_string):
        return _pycodeengine.CodeField_SetBinaryRepresentation(self, byte_string)

    def HasOcrStringRepresentation(self):
        return _pycodeengine.CodeField_HasOcrStringRepresentation(self)

    def GetOcrString(self):
        return _pycodeengine.CodeField_GetOcrString(self)

    def SetOcrStringRepresentation(self, ocr_string):
        return _pycodeengine.CodeField_SetOcrStringRepresentation(self, ocr_string)

# Register CodeField in _pycodeengine:
_pycodeengine.CodeField_swigregister(CodeField)
class CodeFieldsMapIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeFieldsMapIterator

    def __init__(self, other):
        _pycodeengine.CodeFieldsMapIterator_swiginit(self, _pycodeengine.new_CodeFieldsMapIterator(other))

    def GetKey(self):
        return _pycodeengine.CodeFieldsMapIterator_GetKey(self)

    def GetValue(self):
        return _pycodeengine.CodeFieldsMapIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.CodeFieldsMapIterator_Equals(self, rvalue)

    def __eq__(self, other):
        return _pycodeengine.CodeFieldsMapIterator___eq__(self, other)

    def __ne__(self, other):
        return _pycodeengine.CodeFieldsMapIterator___ne__(self, other)

    def Advance(self):
        return _pycodeengine.CodeFieldsMapIterator_Advance(self)

# Register CodeFieldsMapIterator in _pycodeengine:
_pycodeengine.CodeFieldsMapIterator_swigregister(CodeFieldsMapIterator)
CodeObject_LinearBarcode = _pycodeengine.CodeObject_LinearBarcode
CodeObject_MatrixBarcode = _pycodeengine.CodeObject_MatrixBarcode
CodeObject_CodeTextLine = _pycodeengine.CodeObject_CodeTextLine
CodeObject_MRZ = _pycodeengine.CodeObject_MRZ
CodeObject_BankCard = _pycodeengine.CodeObject_BankCard
CodeObject_PaymentDetails = _pycodeengine.CodeObject_PaymentDetails
CodeObject_Face = _pycodeengine.CodeObject_Face
CodeObject_Container = _pycodeengine.CodeObject_Container
class CodeObject(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.CodeObject_swiginit(self, _pycodeengine.new_CodeObject(*args))
    __swig_destroy__ = _pycodeengine.delete_CodeObject

    def __eq__(self, other):
        return _pycodeengine.CodeObject___eq__(self, other)

    def __ne__(self, other):
        return _pycodeengine.CodeObject___ne__(self, other)

    def GetID(self):
        return _pycodeengine.CodeObject_GetID(self)

    def GetType(self):
        return _pycodeengine.CodeObject_GetType(self)

    def GetTypeStr(self):
        return _pycodeengine.CodeObject_GetTypeStr(self)

    def GetName(self):
        return _pycodeengine.CodeObject_GetName(self)

    def IsAccepted(self):
        return _pycodeengine.CodeObject_IsAccepted(self)

    def IsValidated(self):
        return _pycodeengine.CodeObject_IsValidated(self)

    def GetConfidence(self):
        return _pycodeengine.CodeObject_GetConfidence(self)

    def SetFirstDetectedFrame(self, frame_number):
        return _pycodeengine.CodeObject_SetFirstDetectedFrame(self, frame_number)

    def SetLastUpdatedFrame(self, frame_number):
        return _pycodeengine.CodeObject_SetLastUpdatedFrame(self, frame_number)

    def GetFirstDetectedFrame(self):
        return _pycodeengine.CodeObject_GetFirstDetectedFrame(self)

    def GetLastUpdatedFrame(self):
        return _pycodeengine.CodeObject_GetLastUpdatedFrame(self)

    def GetIsTerminal(self):
        return _pycodeengine.CodeObject_GetIsTerminal(self)

    def SetIsTerminal(self, is_terminal):
        return _pycodeengine.CodeObject_SetIsTerminal(self, is_terminal)

    def HasQuadrangle(self):
        return _pycodeengine.CodeObject_HasQuadrangle(self)

    def GetQuadrangle(self):
        return _pycodeengine.CodeObject_GetQuadrangle(self)

    def SetQuadrangle(self, quad):
        return _pycodeengine.CodeObject_SetQuadrangle(self, quad)

    def HasImage(self):
        return _pycodeengine.CodeObject_HasImage(self)

    def GetImage(self):
        return _pycodeengine.CodeObject_GetImage(self)

    def SetImage(self, img):
        return _pycodeengine.CodeObject_SetImage(self, img)

    def RemoveImage(self):
        return _pycodeengine.CodeObject_RemoveImage(self)

    def GetComponentsCount(self):
        return _pycodeengine.CodeObject_GetComponentsCount(self)

    def GetComponent(self, comp_name):
        return _pycodeengine.CodeObject_GetComponent(self, comp_name)

    def SetComponent(self, comp_name, comp):
        return _pycodeengine.CodeObject_SetComponent(self, comp_name, comp)

    def HasComponent(self, comp_name):
        return _pycodeengine.CodeObject_HasComponent(self, comp_name)

    def ComponentsBegin(self):
        return _pycodeengine.CodeObject_ComponentsBegin(self)

    def ComponentsEnd(self):
        return _pycodeengine.CodeObject_ComponentsEnd(self)

    def GetFieldsCount(self):
        return _pycodeengine.CodeObject_GetFieldsCount(self)

    def GetField(self, field_name):
        return _pycodeengine.CodeObject_GetField(self, field_name)

    def SetField(self, field_name, code_field):
        return _pycodeengine.CodeObject_SetField(self, field_name, code_field)

    def HasField(self, field_name):
        return _pycodeengine.CodeObject_HasField(self, field_name)

    def RemoveField(self, field_name):
        return _pycodeengine.CodeObject_RemoveField(self, field_name)

    def FieldsBegin(self):
        return _pycodeengine.CodeObject_FieldsBegin(self)

    def FieldsEnd(self):
        return _pycodeengine.CodeObject_FieldsEnd(self)

    def GetAttributesCount(self):
        return _pycodeengine.CodeObject_GetAttributesCount(self)

    def GetAttribute(self, attr_name):
        return _pycodeengine.CodeObject_GetAttribute(self, attr_name)

    def HasAttribute(self, attr_name):
        return _pycodeengine.CodeObject_HasAttribute(self, attr_name)

    def SetAttribute(self, attr_name, attr_value):
        return _pycodeengine.CodeObject_SetAttribute(self, attr_name, attr_value)

    def AttributesBegin(self):
        return _pycodeengine.CodeObject_AttributesBegin(self)

    def AttributesEnd(self):
        return _pycodeengine.CodeObject_AttributesEnd(self)

# Register CodeObject in _pycodeengine:
_pycodeengine.CodeObject_swigregister(CodeObject)
class CodeObjectsMapIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeObjectsMapIterator

    def __init__(self, other):
        _pycodeengine.CodeObjectsMapIterator_swiginit(self, _pycodeengine.new_CodeObjectsMapIterator(other))

    def GetKey(self):
        return _pycodeengine.CodeObjectsMapIterator_GetKey(self)

    def GetValue(self):
        return _pycodeengine.CodeObjectsMapIterator_GetValue(self)

    def Equals(self, rvalue):
        return _pycodeengine.CodeObjectsMapIterator_Equals(self, rvalue)

    def __eq__(self, other):
        return _pycodeengine.CodeObjectsMapIterator___eq__(self, other)

    def __ne__(self, other):
        return _pycodeengine.CodeObjectsMapIterator___ne__(self, other)

    def Advance(self):
        return _pycodeengine.CodeObjectsMapIterator_Advance(self)

# Register CodeObjectsMapIterator in _pycodeengine:
_pycodeengine.CodeObjectsMapIterator_swigregister(CodeObjectsMapIterator)
class CodeEngineResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _pycodeengine.CodeEngineResult_swiginit(self, _pycodeengine.new_CodeEngineResult(*args))
    __swig_destroy__ = _pycodeengine.delete_CodeEngineResult

    def __eq__(self, other):
        return _pycodeengine.CodeEngineResult___eq__(self, other)

    def __ne__(self, other):
        return _pycodeengine.CodeEngineResult___ne__(self, other)

    def GetObjectCount(self):
        return _pycodeengine.CodeEngineResult_GetObjectCount(self)

    def HasObject(self, object_name):
        return _pycodeengine.CodeEngineResult_HasObject(self, object_name)

    def GetCodeObject(self, object_name):
        return _pycodeengine.CodeEngineResult_GetCodeObject(self, object_name)

    def SetCodeObject(self, object_name, code_object):
        return _pycodeengine.CodeEngineResult_SetCodeObject(self, object_name, code_object)

    def ObjectsBegin(self):
        return _pycodeengine.CodeEngineResult_ObjectsBegin(self)

    def ObjectsEnd(self):
        return _pycodeengine.CodeEngineResult_ObjectsEnd(self)

    def IsTerminal(self):
        return _pycodeengine.CodeEngineResult_IsTerminal(self)

    def SetTerminal(self, terminal=True):
        return _pycodeengine.CodeEngineResult_SetTerminal(self, terminal)

    def Reset(self):
        return _pycodeengine.CodeEngineResult_Reset(self)

# Register CodeEngineResult in _pycodeengine:
_pycodeengine.CodeEngineResult_swigregister(CodeEngineResult)
class CodeEngineSession(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeEngineSession

    def GetActivationRequest(self):
        return _pycodeengine.CodeEngineSession_GetActivationRequest(self)

    def Activate(self, activation_response):
        return _pycodeengine.CodeEngineSession_Activate(self, activation_response)

    def IsActivated(self):
        return _pycodeengine.CodeEngineSession_IsActivated(self)

    def Process(self, image):
        return _pycodeengine.CodeEngineSession_Process(self, image)

    def GetCurrentResult(self):
        return _pycodeengine.CodeEngineSession_GetCurrentResult(self)

    def IsResultTerminal(self):
        return _pycodeengine.CodeEngineSession_IsResultTerminal(self)

    def Reset(self):
        return _pycodeengine.CodeEngineSession_Reset(self)

# Register CodeEngineSession in _pycodeengine:
_pycodeengine.CodeEngineSession_swigregister(CodeEngineSession)
class CodeEngineFeedbackContainer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeEngineFeedbackContainer

    def __init__(self, *args):
        _pycodeengine.CodeEngineFeedbackContainer_swiginit(self, _pycodeengine.new_CodeEngineFeedbackContainer(*args))

    def GetQuadranglesCount(self):
        return _pycodeengine.CodeEngineFeedbackContainer_GetQuadranglesCount(self)

    def HasQuadrangle(self, quad_name):
        return _pycodeengine.CodeEngineFeedbackContainer_HasQuadrangle(self, quad_name)

    def GetQuadrangle(self, quad_name):
        return _pycodeengine.CodeEngineFeedbackContainer_GetQuadrangle(self, quad_name)

    def SetQuadrangle(self, quad_name, quad):
        return _pycodeengine.CodeEngineFeedbackContainer_SetQuadrangle(self, quad_name, quad)

    def RemoveQuadrangle(self, quad_name):
        return _pycodeengine.CodeEngineFeedbackContainer_RemoveQuadrangle(self, quad_name)

    def QuadranglesBegin(self):
        return _pycodeengine.CodeEngineFeedbackContainer_QuadranglesBegin(self)

    def QuadranglesEnd(self):
        return _pycodeengine.CodeEngineFeedbackContainer_QuadranglesEnd(self)

# Register CodeEngineFeedbackContainer in _pycodeengine:
_pycodeengine.CodeEngineFeedbackContainer_swigregister(CodeEngineFeedbackContainer)
class CodeEngineVisualizationFeedback(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeEngineVisualizationFeedback

    def FeedbackReceived(self, feedback_container):
        return _pycodeengine.CodeEngineVisualizationFeedback_FeedbackReceived(self, feedback_container)

    def __init__(self):
        if self.__class__ == CodeEngineVisualizationFeedback:
            _self = None
        else:
            _self = self
        _pycodeengine.CodeEngineVisualizationFeedback_swiginit(self, _pycodeengine.new_CodeEngineVisualizationFeedback(_self, ))
    def __disown__(self):
        self.this.disown()
        _pycodeengine.disown_CodeEngineVisualizationFeedback(self)
        return weakref.proxy(self)

# Register CodeEngineVisualizationFeedback in _pycodeengine:
_pycodeengine.CodeEngineVisualizationFeedback_swigregister(CodeEngineVisualizationFeedback)
class CodeEngineWorkflowFeedback(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycodeengine.delete_CodeEngineWorkflowFeedback

    def ResultReceived(self, result_received):
        return _pycodeengine.CodeEngineWorkflowFeedback_ResultReceived(self, result_received)

    def SessionEnded(self):
        return _pycodeengine.CodeEngineWorkflowFeedback_SessionEnded(self)

    def __init__(self):
        if self.__class__ == CodeEngineWorkflowFeedback:
            _self = None
        else:
            _self = self
        _pycodeengine.CodeEngineWorkflowFeedback_swiginit(self, _pycodeengine.new_CodeEngineWorkflowFeedback(_self, ))
    def __disown__(self):
        self.this.disown()
        _pycodeengine.disown_CodeEngineWorkflowFeedback(self)
        return weakref.proxy(self)

# Register CodeEngineWorkflowFeedback in _pycodeengine:
_pycodeengine.CodeEngineWorkflowFeedback_swigregister(CodeEngineWorkflowFeedback)
CodeEngine_Barcode = _pycodeengine.CodeEngine_Barcode
CodeEngine_CodeTextLine = _pycodeengine.CodeEngine_CodeTextLine
CodeEngine_MRZ = _pycodeengine.CodeEngine_MRZ
CodeEngine_BankCard = _pycodeengine.CodeEngine_BankCard
CodeEngine_PaymentDetails = _pycodeengine.CodeEngine_PaymentDetails
CodeEngine_LicensePlate = _pycodeengine.CodeEngine_LicensePlate
CodeEngine_ShippingContainer = _pycodeengine.CodeEngine_ShippingContainer
EngineSettingsGroup_Global = _pycodeengine.EngineSettingsGroup_Global
EngineSettingsGroup_Barcode = _pycodeengine.EngineSettingsGroup_Barcode
EngineSettingsGroup_Card = _pycodeengine.EngineSettingsGroup_Card
EngineSettingsGroup_CodeTextLine = _pycodeengine.EngineSettingsGroup_CodeTextLine
EngineSettingsGroup_Mrz = _pycodeengine.EngineSettingsGroup_Mrz
EngineSettingsGroup_PaymentDetails = _pycodeengine.EngineSettingsGroup_PaymentDetails
EngineSettingsGroup_LicensePlate = _pycodeengine.EngineSettingsGroup_LicensePlate
EngineSettingsGroup_ShippingContainer = _pycodeengine.EngineSettingsGroup_ShippingContainer
BarcodePreset_GS1 = _pycodeengine.BarcodePreset_GS1
BarcodePreset_AAMVA = _pycodeengine.BarcodePreset_AAMVA
BarcodePreset_URL = _pycodeengine.BarcodePreset_URL
BarcodePreset_VCARD = _pycodeengine.BarcodePreset_VCARD
BarcodePreset_EMAIL = _pycodeengine.BarcodePreset_EMAIL
BarcodePreset_ICALENDAR = _pycodeengine.BarcodePreset_ICALENDAR
BarcodePreset_PHONE = _pycodeengine.BarcodePreset_PHONE
BarcodePreset_SMS = _pycodeengine.BarcodePreset_SMS
BarcodePreset_ISBN = _pycodeengine.BarcodePreset_ISBN
BarcodePreset_WIFI = _pycodeengine.BarcodePreset_WIFI
BarcodePreset_GEO = _pycodeengine.BarcodePreset_GEO
BarcodePreset_PAYMENT = _pycodeengine.BarcodePreset_PAYMENT
BarcodePreset_NONE = _pycodeengine.BarcodePreset_NONE

def engineSettingsGroupFromString(group_name):
    return _pycodeengine.engineSettingsGroupFromString(group_name)

def toString(group):
    return _pycodeengine.toString(group)

def presetToString(preset):
    return _pycodeengine.presetToString(preset)
class CodeEngine(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def Create(*args):
        return _pycodeengine.CodeEngine_Create(*args)

    @staticmethod
    def CreateFromEmbeddedBundle(lazy_configuration=True):
        return _pycodeengine.CodeEngine_CreateFromEmbeddedBundle(lazy_configuration)
    __swig_destroy__ = _pycodeengine.delete_CodeEngine

    @staticmethod
    def GetVersion():
        return _pycodeengine.CodeEngine_GetVersion()

    def GetDefaultSessionSettings(self):
        return _pycodeengine.CodeEngine_GetDefaultSessionSettings(self)

    def SpawnSession(self, settings, signature, workflow_reporter=None, visualization_reporter=None):
        return _pycodeengine.CodeEngine_SpawnSession(self, settings, signature, workflow_reporter, visualization_reporter)

    def IsEngineAvailable(self, engine_type):
        return _pycodeengine.CodeEngine_IsEngineAvailable(self, engine_type)

# Register CodeEngine in _pycodeengine:
_pycodeengine.CodeEngine_swigregister(CodeEngine)

