//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeEngineResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeEngineResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeEngineResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeEngineResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeEngineResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeEngineResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CodeEngineResult(bool is_terminal) : this(cscodeenginePINVOKE.new_CodeEngineResult__SWIG_0(is_terminal), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeEngineResult() : this(cscodeenginePINVOKE.new_CodeEngineResult__SWIG_1(), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeEngineResult(CodeEngineResult other) : this(cscodeenginePINVOKE.new_CodeEngineResult__SWIG_2(CodeEngineResult.getCPtr(other)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetObjectCount() {
    int ret = cscodeenginePINVOKE.CodeEngineResult_GetObjectCount(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasObject(string object_name) {
    bool ret = cscodeenginePINVOKE.CodeEngineResult_HasObject(swigCPtr, object_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CodeObject GetCodeObject(string object_name) {
    CodeObject ret = new CodeObject(cscodeenginePINVOKE.CodeEngineResult_GetCodeObject(swigCPtr, object_name), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetCodeObject(string object_name, CodeObject code_object) {
    cscodeenginePINVOKE.CodeEngineResult_SetCodeObject(swigCPtr, object_name, CodeObject.getCPtr(code_object));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeObjectsMapIterator ObjectsBegin() {
    CodeObjectsMapIterator ret = new CodeObjectsMapIterator(cscodeenginePINVOKE.CodeEngineResult_ObjectsBegin(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CodeObjectsMapIterator ObjectsEnd() {
    CodeObjectsMapIterator ret = new CodeObjectsMapIterator(cscodeenginePINVOKE.CodeEngineResult_ObjectsEnd(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsTerminal() {
    bool ret = cscodeenginePINVOKE.CodeEngineResult_IsTerminal(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetTerminal(bool terminal) {
    cscodeenginePINVOKE.CodeEngineResult_SetTerminal__SWIG_0(swigCPtr, terminal);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTerminal() {
    cscodeenginePINVOKE.CodeEngineResult_SetTerminal__SWIG_1(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reset() {
    cscodeenginePINVOKE.CodeEngineResult_Reset(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
