//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class StringVector2d : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<StringVector>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public StringVector2d(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(StringVector2d obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(StringVector2d obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~StringVector2d() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_StringVector2d(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public StringVector2d(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (StringVector element in c) {
      this.Add(element);
    }
  }

  public StringVector2d(global::System.Collections.Generic.IEnumerable<StringVector> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (StringVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public StringVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(StringVector[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(StringVector[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, StringVector[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public StringVector[] ToArray() {
    StringVector[] array = new StringVector[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<StringVector> global::System.Collections.Generic.IEnumerable<StringVector>.GetEnumerator() {
    return new StringVector2dEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new StringVector2dEnumerator(this);
  }

  public StringVector2dEnumerator GetEnumerator() {
    return new StringVector2dEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class StringVector2dEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<StringVector>
  {
    private StringVector2d collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public StringVector2dEnumerator(StringVector2d collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public StringVector Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (StringVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    cscodeenginePINVOKE.StringVector2d_Clear(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(StringVector x) {
    cscodeenginePINVOKE.StringVector2d_Add(swigCPtr, StringVector.getCPtr(x));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = cscodeenginePINVOKE.StringVector2d_size(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = cscodeenginePINVOKE.StringVector2d_capacity(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    cscodeenginePINVOKE.StringVector2d_reserve(swigCPtr, n);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector2d() : this(cscodeenginePINVOKE.new_StringVector2d__SWIG_0(), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector2d(StringVector2d other) : this(cscodeenginePINVOKE.new_StringVector2d__SWIG_1(StringVector2d.getCPtr(other)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector2d(int capacity) : this(cscodeenginePINVOKE.new_StringVector2d__SWIG_2(capacity), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  private StringVector getitemcopy(int index) {
    StringVector ret = new StringVector(cscodeenginePINVOKE.StringVector2d_getitemcopy(swigCPtr, index), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private StringVector getitem(int index) {
    StringVector ret = new StringVector(cscodeenginePINVOKE.StringVector2d_getitem(swigCPtr, index), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, StringVector val) {
    cscodeenginePINVOKE.StringVector2d_setitem(swigCPtr, index, StringVector.getCPtr(val));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(StringVector2d values) {
    cscodeenginePINVOKE.StringVector2d_AddRange(swigCPtr, StringVector2d.getCPtr(values));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public StringVector2d GetRange(int index, int count) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.StringVector2d_GetRange(swigCPtr, index, count);
    StringVector2d ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector2d(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, StringVector x) {
    cscodeenginePINVOKE.StringVector2d_Insert(swigCPtr, index, StringVector.getCPtr(x));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, StringVector2d values) {
    cscodeenginePINVOKE.StringVector2d_InsertRange(swigCPtr, index, StringVector2d.getCPtr(values));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    cscodeenginePINVOKE.StringVector2d_RemoveAt(swigCPtr, index);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    cscodeenginePINVOKE.StringVector2d_RemoveRange(swigCPtr, index, count);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public static StringVector2d Repeat(StringVector value, int count) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.StringVector2d_Repeat(StringVector.getCPtr(value), count);
    StringVector2d ret = (cPtr == global::System.IntPtr.Zero) ? null : new StringVector2d(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    cscodeenginePINVOKE.StringVector2d_Reverse__SWIG_0(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    cscodeenginePINVOKE.StringVector2d_Reverse__SWIG_1(swigCPtr, index, count);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, StringVector2d values) {
    cscodeenginePINVOKE.StringVector2d_SetRange(swigCPtr, index, StringVector2d.getCPtr(values));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
