//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeObject : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeObject(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeObject obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeObject() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CodeObject() : this(cscodeenginePINVOKE.new_CodeObject__SWIG_0(), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeObject(string name, CodeObjectType object_type, bool is_accepted, float confidence) : this(cscodeenginePINVOKE.new_CodeObject__SWIG_1(name, (int)object_type, is_accepted, confidence), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeObject(string name, CodeObjectType object_type, bool is_accepted) : this(cscodeenginePINVOKE.new_CodeObject__SWIG_2(name, (int)object_type, is_accepted), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeObject(string name, CodeObjectType object_type) : this(cscodeenginePINVOKE.new_CodeObject__SWIG_3(name, (int)object_type), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeObject(CodeObject other) : this(cscodeenginePINVOKE.new_CodeObject__SWIG_4(CodeObject.getCPtr(other)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetID() {
    int ret = cscodeenginePINVOKE.CodeObject_GetID(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CodeObjectType GetType() {
    CodeObjectType ret = (CodeObjectType)cscodeenginePINVOKE.CodeObject_GetType(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetTypeStr() {
    string ret = cscodeenginePINVOKE.CodeObject_GetTypeStr(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetName() {
    string ret = cscodeenginePINVOKE.CodeObject_GetName(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsAccepted() {
    bool ret = cscodeenginePINVOKE.CodeObject_IsAccepted(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool IsValidated() {
    bool ret = cscodeenginePINVOKE.CodeObject_IsValidated(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float GetConfidence() {
    float ret = cscodeenginePINVOKE.CodeObject_GetConfidence(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetFirstDetectedFrame(int frame_number) {
    cscodeenginePINVOKE.CodeObject_SetFirstDetectedFrame(swigCPtr, frame_number);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetLastUpdatedFrame(int frame_number) {
    cscodeenginePINVOKE.CodeObject_SetLastUpdatedFrame(swigCPtr, frame_number);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetFirstDetectedFrame() {
    int ret = cscodeenginePINVOKE.CodeObject_GetFirstDetectedFrame(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetLastUpdatedFrame() {
    int ret = cscodeenginePINVOKE.CodeObject_GetLastUpdatedFrame(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetIsTerminal() {
    bool ret = cscodeenginePINVOKE.CodeObject_GetIsTerminal(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsTerminal(bool is_terminal) {
    cscodeenginePINVOKE.CodeObject_SetIsTerminal(swigCPtr, is_terminal);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasQuadrangle() {
    bool ret = cscodeenginePINVOKE.CodeObject_HasQuadrangle(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Quadrangle GetQuadrangle() {
    Quadrangle ret = new Quadrangle(cscodeenginePINVOKE.CodeObject_GetQuadrangle(swigCPtr), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetQuadrangle(Quadrangle quad) {
    cscodeenginePINVOKE.CodeObject_SetQuadrangle(swigCPtr, Quadrangle.getCPtr(quad));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasImage() {
    bool ret = cscodeenginePINVOKE.CodeObject_HasImage(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Image GetImage() {
    Image ret = new Image(cscodeenginePINVOKE.CodeObject_GetImage(swigCPtr), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetImage(Image img) {
    cscodeenginePINVOKE.CodeObject_SetImage(swigCPtr, Image.getCPtr(img));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveImage() {
    cscodeenginePINVOKE.CodeObject_RemoveImage(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetComponentsCount() {
    int ret = cscodeenginePINVOKE.CodeObject_GetComponentsCount(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Quadrangle GetComponent(string comp_name) {
    Quadrangle ret = new Quadrangle(cscodeenginePINVOKE.CodeObject_GetComponent(swigCPtr, comp_name), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetComponent(string comp_name, Quadrangle comp) {
    cscodeenginePINVOKE.CodeObject_SetComponent(swigCPtr, comp_name, Quadrangle.getCPtr(comp));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasComponent(string comp_name) {
    bool ret = cscodeenginePINVOKE.CodeObject_HasComponent(swigCPtr, comp_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public QuadranglesMapIterator ComponentsBegin() {
    QuadranglesMapIterator ret = new QuadranglesMapIterator(cscodeenginePINVOKE.CodeObject_ComponentsBegin(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public QuadranglesMapIterator ComponentsEnd() {
    QuadranglesMapIterator ret = new QuadranglesMapIterator(cscodeenginePINVOKE.CodeObject_ComponentsEnd(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetFieldsCount() {
    int ret = cscodeenginePINVOKE.CodeObject_GetFieldsCount(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CodeField GetField(string field_name) {
    CodeField ret = new CodeField(cscodeenginePINVOKE.CodeObject_GetField(swigCPtr, field_name), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetField(string field_name, CodeField code_field) {
    cscodeenginePINVOKE.CodeObject_SetField(swigCPtr, field_name, CodeField.getCPtr(code_field));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasField(string field_name) {
    bool ret = cscodeenginePINVOKE.CodeObject_HasField(swigCPtr, field_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void RemoveField(string field_name) {
    cscodeenginePINVOKE.CodeObject_RemoveField(swigCPtr, field_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeFieldsMapIterator FieldsBegin() {
    CodeFieldsMapIterator ret = new CodeFieldsMapIterator(cscodeenginePINVOKE.CodeObject_FieldsBegin(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CodeFieldsMapIterator FieldsEnd() {
    CodeFieldsMapIterator ret = new CodeFieldsMapIterator(cscodeenginePINVOKE.CodeObject_FieldsEnd(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetAttributesCount() {
    int ret = cscodeenginePINVOKE.CodeObject_GetAttributesCount(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetAttribute(string attr_name) {
    string ret = cscodeenginePINVOKE.CodeObject_GetAttribute(swigCPtr, attr_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasAttribute(string attr_name) {
    bool ret = cscodeenginePINVOKE.CodeObject_HasAttribute(swigCPtr, attr_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetAttribute(string attr_name, string attr_value) {
    cscodeenginePINVOKE.CodeObject_SetAttribute(swigCPtr, attr_name, attr_value);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public StringsMapIterator AttributesBegin() {
    StringsMapIterator ret = new StringsMapIterator(cscodeenginePINVOKE.CodeObject_AttributesBegin(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public StringsMapIterator AttributesEnd() {
    StringsMapIterator ret = new StringsMapIterator(cscodeenginePINVOKE.CodeObject_AttributesEnd(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
