//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

public enum CodeObjectType {
  CodeObject_LinearBarcode = (1 << 1),
  CodeObject_MatrixBarcode = (1 << 2),
  CodeObject_CodeTextLine = (1 << 3),
  CodeObject_MRZ = (1 << 4),
  CodeObject_BankCard = (1 << 5),
  CodeObject_PaymentDetails = (1 << 6),
  CodeObject_Face = (1 << 7),
  CodeObject_Container = (1 << 8)
}

}
