//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeEngineFeedbackContainer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeEngineFeedbackContainer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeEngineFeedbackContainer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeEngineFeedbackContainer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeEngineFeedbackContainer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeEngineFeedbackContainer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CodeEngineFeedbackContainer() : this(cscodeenginePINVOKE.new_CodeEngineFeedbackContainer__SWIG_0(), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeEngineFeedbackContainer(CodeEngineFeedbackContainer copy) : this(cscodeenginePINVOKE.new_CodeEngineFeedbackContainer__SWIG_1(CodeEngineFeedbackContainer.getCPtr(copy)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetQuadranglesCount() {
    int ret = cscodeenginePINVOKE.CodeEngineFeedbackContainer_GetQuadranglesCount(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool HasQuadrangle(string quad_name) {
    bool ret = cscodeenginePINVOKE.CodeEngineFeedbackContainer_HasQuadrangle(swigCPtr, quad_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Quadrangle GetQuadrangle(string quad_name) {
    Quadrangle ret = new Quadrangle(cscodeenginePINVOKE.CodeEngineFeedbackContainer_GetQuadrangle(swigCPtr, quad_name), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetQuadrangle(string quad_name, Quadrangle quad) {
    cscodeenginePINVOKE.CodeEngineFeedbackContainer_SetQuadrangle(swigCPtr, quad_name, Quadrangle.getCPtr(quad));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveQuadrangle(string quad_name) {
    cscodeenginePINVOKE.CodeEngineFeedbackContainer_RemoveQuadrangle(swigCPtr, quad_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public QuadranglesMapIterator QuadranglesBegin() {
    QuadranglesMapIterator ret = new QuadranglesMapIterator(cscodeenginePINVOKE.CodeEngineFeedbackContainer_QuadranglesBegin(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public QuadranglesMapIterator QuadranglesEnd() {
    QuadranglesMapIterator ret = new QuadranglesMapIterator(cscodeenginePINVOKE.CodeEngineFeedbackContainer_QuadranglesEnd(swigCPtr), true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
