//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeEngine : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeEngine(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeEngine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeEngine obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeEngine() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeEngine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static CodeEngine Create(string config_path, bool lazy_configuration) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_Create__SWIG_0(config_path, lazy_configuration);
    CodeEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngine(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CodeEngine Create(string config_path) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_Create__SWIG_1(config_path);
    CodeEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngine(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CodeEngine Create(byte[] config_data, int config_data_length, bool lazy_configuration) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_Create__SWIG_2(config_data, config_data_length, lazy_configuration);
    CodeEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngine(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CodeEngine Create(byte[] config_data, int config_data_length) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_Create__SWIG_3(config_data, config_data_length);
    CodeEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngine(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CodeEngine CreateFromEmbeddedBundle(bool lazy_configuration) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_CreateFromEmbeddedBundle__SWIG_0(lazy_configuration);
    CodeEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngine(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static CodeEngine CreateFromEmbeddedBundle() {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_CreateFromEmbeddedBundle__SWIG_1();
    CodeEngine ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngine(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string GetVersion() {
    string ret = cscodeenginePINVOKE.CodeEngine_GetVersion();
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual CodeEngineSessionSettings GetDefaultSessionSettings() {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_GetDefaultSessionSettings(swigCPtr);
    CodeEngineSessionSettings ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngineSessionSettings(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual CodeEngineSession SpawnSession(CodeEngineSessionSettings settings, string signature, CodeEngineWorkflowFeedback workflow_reporter, CodeEngineVisualizationFeedback visualization_reporter) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_SpawnSession__SWIG_0(swigCPtr, CodeEngineSessionSettings.getCPtr(settings), signature, CodeEngineWorkflowFeedback.getCPtr(workflow_reporter), CodeEngineVisualizationFeedback.getCPtr(visualization_reporter));
    CodeEngineSession ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngineSession(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual CodeEngineSession SpawnSession(CodeEngineSessionSettings settings, string signature, CodeEngineWorkflowFeedback workflow_reporter) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_SpawnSession__SWIG_1(swigCPtr, CodeEngineSessionSettings.getCPtr(settings), signature, CodeEngineWorkflowFeedback.getCPtr(workflow_reporter));
    CodeEngineSession ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngineSession(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual CodeEngineSession SpawnSession(CodeEngineSessionSettings settings, string signature) {
    global::System.IntPtr cPtr = cscodeenginePINVOKE.CodeEngine_SpawnSession__SWIG_2(swigCPtr, CodeEngineSessionSettings.getCPtr(settings), signature);
    CodeEngineSession ret = (cPtr == global::System.IntPtr.Zero) ? null : new CodeEngineSession(cPtr, true);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool IsEngineAvailable(CodeEngineType engine_type) {
    bool ret = cscodeenginePINVOKE.CodeEngine_IsEngineAvailable(swigCPtr, (int)engine_type);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
