//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

public class CodeField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public CodeField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(CodeField obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public static global::System.Runtime.InteropServices.HandleRef swigRelease(CodeField obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CodeField() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cscodeenginePINVOKE.delete_CodeField(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CodeField() : this(cscodeenginePINVOKE.new_CodeField__SWIG_0(), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(string name, ByteString byte_string, bool is_accepted, float confidence) : this(cscodeenginePINVOKE.new_CodeField__SWIG_1(name, ByteString.getCPtr(byte_string), is_accepted, confidence), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(string name, ByteString byte_string, bool is_accepted) : this(cscodeenginePINVOKE.new_CodeField__SWIG_2(name, ByteString.getCPtr(byte_string), is_accepted), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(string name, ByteString byte_string) : this(cscodeenginePINVOKE.new_CodeField__SWIG_3(name, ByteString.getCPtr(byte_string)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(string name, OcrString ocr_string, bool is_accepted, float confidence) : this(cscodeenginePINVOKE.new_CodeField__SWIG_4(name, OcrString.getCPtr(ocr_string), is_accepted, confidence), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(string name, OcrString ocr_string, bool is_accepted) : this(cscodeenginePINVOKE.new_CodeField__SWIG_5(name, OcrString.getCPtr(ocr_string), is_accepted), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(string name, OcrString ocr_string) : this(cscodeenginePINVOKE.new_CodeField__SWIG_6(name, OcrString.getCPtr(ocr_string)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public CodeField(CodeField copy) : this(cscodeenginePINVOKE.new_CodeField__SWIG_7(CodeField.getCPtr(copy)), true) {
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string Name() {
    string ret = cscodeenginePINVOKE.CodeField_Name(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetName(string name) {
    cscodeenginePINVOKE.CodeField_SetName(swigCPtr, name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsAccepted() {
    bool ret = cscodeenginePINVOKE.CodeField_IsAccepted(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsAccepted(bool is_accepted) {
    cscodeenginePINVOKE.CodeField_SetIsAccepted(swigCPtr, is_accepted);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetConfidence() {
    double ret = cscodeenginePINVOKE.CodeField_GetConfidence(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetConfidence(float confidence) {
    cscodeenginePINVOKE.CodeField_SetConfidence(swigCPtr, confidence);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsTerminal() {
    bool ret = cscodeenginePINVOKE.CodeField_IsTerminal(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetIsTerminal(bool is_terminal) {
    cscodeenginePINVOKE.CodeField_SetIsTerminal(swigCPtr, is_terminal);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasBinaryRepresentation() {
    bool ret = cscodeenginePINVOKE.CodeField_HasBinaryRepresentation(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ByteString GetBinaryRepresentation() {
    ByteString ret = new ByteString(cscodeenginePINVOKE.CodeField_GetBinaryRepresentation(swigCPtr), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetBinaryRepresentation(ByteString byte_string) {
    cscodeenginePINVOKE.CodeField_SetBinaryRepresentation(swigCPtr, ByteString.getCPtr(byte_string));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool HasOcrStringRepresentation() {
    bool ret = cscodeenginePINVOKE.CodeField_HasOcrStringRepresentation(swigCPtr);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public OcrString GetOcrString() {
    OcrString ret = new OcrString(cscodeenginePINVOKE.CodeField_GetOcrString(swigCPtr), false);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetOcrStringRepresentation(OcrString ocr_string) {
    cscodeenginePINVOKE.CodeField_SetOcrStringRepresentation(swigCPtr, OcrString.getCPtr(ocr_string));
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
