//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

public class cscodeengine {
  public static EngineSettingsGroup engineSettingsGroupFromString(string group_name) {
    EngineSettingsGroup ret = (EngineSettingsGroup)cscodeenginePINVOKE.engineSettingsGroupFromString(group_name);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string toString(EngineSettingsGroup group) {
    string ret = cscodeenginePINVOKE.toString((int)group);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string presetToString(BarcodePreset preset) {
    string ret = cscodeenginePINVOKE.presetToString((int)preset);
    if (cscodeenginePINVOKE.SWIGPendingException.Pending) throw cscodeenginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
