/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

public class jnicodeengine {
  public static EngineSettingsGroup engineSettingsGroupFromString(String group_name) {
    return EngineSettingsGroup.swigToEnum(jnicodeengineJNI.engineSettingsGroupFromString(group_name));
  }

  public static String toString(EngineSettingsGroup group) {
    return jnicodeengineJNI.toString(group.swigValue());
  }

  public static String presetToString(BarcodePreset preset) {
    return jnicodeengineJNI.presetToString(preset.swigValue());
  }

}
