/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class jnicodeengineJNI {
  public final static native void delete_CodeEngineSessionSettings(long jarg1);
  public final static native long CodeEngineSessionSettings_Clone(long jarg1, CodeEngineSessionSettings jarg1_);
  public final static native String CodeEngineSessionSettings_GetOption(long jarg1, CodeEngineSessionSettings jarg1_, String jarg2);
  public final static native long CodeEngineSessionSettings_SettingsBegin(long jarg1, CodeEngineSessionSettings jarg1_);
  public final static native long CodeEngineSessionSettings_SettingsEnd(long jarg1, CodeEngineSessionSettings jarg1_);
  public final static native boolean CodeEngineSessionSettings_HasOption(long jarg1, CodeEngineSessionSettings jarg1_, String jarg2);
  public final static native void CodeEngineSessionSettings_SetOption(long jarg1, CodeEngineSessionSettings jarg1_, String jarg2, String jarg3);
  public final static native long new_CodeField__SWIG_0();
  public final static native long new_CodeField__SWIG_1(String jarg1, long jarg2, ByteString jarg2_, boolean jarg3, float jarg4);
  public final static native long new_CodeField__SWIG_2(String jarg1, long jarg2, ByteString jarg2_, boolean jarg3);
  public final static native long new_CodeField__SWIG_3(String jarg1, long jarg2, ByteString jarg2_);
  public final static native long new_CodeField__SWIG_4(String jarg1, long jarg2, OcrString jarg2_, boolean jarg3, float jarg4);
  public final static native long new_CodeField__SWIG_5(String jarg1, long jarg2, OcrString jarg2_, boolean jarg3);
  public final static native long new_CodeField__SWIG_6(String jarg1, long jarg2, OcrString jarg2_);
  public final static native void delete_CodeField(long jarg1);
  public final static native long new_CodeField__SWIG_7(long jarg1, CodeField jarg1_);
  public final static native String CodeField_Name(long jarg1, CodeField jarg1_);
  public final static native void CodeField_SetName(long jarg1, CodeField jarg1_, String jarg2);
  public final static native boolean CodeField_IsAccepted(long jarg1, CodeField jarg1_);
  public final static native void CodeField_SetIsAccepted(long jarg1, CodeField jarg1_, boolean jarg2);
  public final static native double CodeField_GetConfidence(long jarg1, CodeField jarg1_);
  public final static native void CodeField_SetConfidence(long jarg1, CodeField jarg1_, float jarg2);
  public final static native boolean CodeField_IsTerminal(long jarg1, CodeField jarg1_);
  public final static native void CodeField_SetIsTerminal(long jarg1, CodeField jarg1_, boolean jarg2);
  public final static native boolean CodeField_HasBinaryRepresentation(long jarg1, CodeField jarg1_);
  public final static native long CodeField_GetBinaryRepresentation(long jarg1, CodeField jarg1_);
  public final static native void CodeField_SetBinaryRepresentation(long jarg1, CodeField jarg1_, long jarg2, ByteString jarg2_);
  public final static native boolean CodeField_HasOcrStringRepresentation(long jarg1, CodeField jarg1_);
  public final static native long CodeField_GetOcrString(long jarg1, CodeField jarg1_);
  public final static native void CodeField_SetOcrStringRepresentation(long jarg1, CodeField jarg1_, long jarg2, OcrString jarg2_);
  public final static native void delete_CodeFieldsMapIterator(long jarg1);
  public final static native long new_CodeFieldsMapIterator(long jarg1, CodeFieldsMapIterator jarg1_);
  public final static native String CodeFieldsMapIterator_GetKey(long jarg1, CodeFieldsMapIterator jarg1_);
  public final static native long CodeFieldsMapIterator_GetValue(long jarg1, CodeFieldsMapIterator jarg1_);
  public final static native boolean CodeFieldsMapIterator_Equals(long jarg1, CodeFieldsMapIterator jarg1_, long jarg2, CodeFieldsMapIterator jarg2_);
  public final static native void CodeFieldsMapIterator_Advance(long jarg1, CodeFieldsMapIterator jarg1_);
  public final static native int CodeObject_LinearBarcode_get();
  public final static native int CodeObject_MatrixBarcode_get();
  public final static native int CodeObject_CodeTextLine_get();
  public final static native int CodeObject_MRZ_get();
  public final static native int CodeObject_BankCard_get();
  public final static native int CodeObject_PaymentDetails_get();
  public final static native int CodeObject_Face_get();
  public final static native int CodeObject_Container_get();
  public final static native long new_CodeObject__SWIG_0();
  public final static native long new_CodeObject__SWIG_1(String jarg1, int jarg2, boolean jarg3, float jarg4);
  public final static native long new_CodeObject__SWIG_2(String jarg1, int jarg2, boolean jarg3);
  public final static native long new_CodeObject__SWIG_3(String jarg1, int jarg2);
  public final static native long new_CodeObject__SWIG_4(long jarg1, CodeObject jarg1_);
  public final static native void delete_CodeObject(long jarg1);
  public final static native int CodeObject_GetID(long jarg1, CodeObject jarg1_);
  public final static native int CodeObject_GetType(long jarg1, CodeObject jarg1_);
  public final static native String CodeObject_GetTypeStr(long jarg1, CodeObject jarg1_);
  public final static native String CodeObject_GetName(long jarg1, CodeObject jarg1_);
  public final static native boolean CodeObject_IsAccepted(long jarg1, CodeObject jarg1_);
  public final static native boolean CodeObject_IsValidated(long jarg1, CodeObject jarg1_);
  public final static native float CodeObject_GetConfidence(long jarg1, CodeObject jarg1_);
  public final static native void CodeObject_SetFirstDetectedFrame(long jarg1, CodeObject jarg1_, int jarg2);
  public final static native void CodeObject_SetLastUpdatedFrame(long jarg1, CodeObject jarg1_, int jarg2);
  public final static native int CodeObject_GetFirstDetectedFrame(long jarg1, CodeObject jarg1_);
  public final static native int CodeObject_GetLastUpdatedFrame(long jarg1, CodeObject jarg1_);
  public final static native boolean CodeObject_GetIsTerminal(long jarg1, CodeObject jarg1_);
  public final static native void CodeObject_SetIsTerminal(long jarg1, CodeObject jarg1_, boolean jarg2);
  public final static native boolean CodeObject_HasQuadrangle(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_GetQuadrangle(long jarg1, CodeObject jarg1_);
  public final static native void CodeObject_SetQuadrangle(long jarg1, CodeObject jarg1_, long jarg2, Quadrangle jarg2_);
  public final static native boolean CodeObject_HasImage(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_GetImage(long jarg1, CodeObject jarg1_);
  public final static native void CodeObject_SetImage(long jarg1, CodeObject jarg1_, long jarg2, Image jarg2_);
  public final static native void CodeObject_RemoveImage(long jarg1, CodeObject jarg1_);
  public final static native int CodeObject_GetComponentsCount(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_GetComponent(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native void CodeObject_SetComponent(long jarg1, CodeObject jarg1_, String jarg2, long jarg3, Quadrangle jarg3_);
  public final static native boolean CodeObject_HasComponent(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native long CodeObject_ComponentsBegin(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_ComponentsEnd(long jarg1, CodeObject jarg1_);
  public final static native int CodeObject_GetFieldsCount(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_GetField(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native void CodeObject_SetField(long jarg1, CodeObject jarg1_, String jarg2, long jarg3, CodeField jarg3_);
  public final static native boolean CodeObject_HasField(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native void CodeObject_RemoveField(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native long CodeObject_FieldsBegin(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_FieldsEnd(long jarg1, CodeObject jarg1_);
  public final static native int CodeObject_GetAttributesCount(long jarg1, CodeObject jarg1_);
  public final static native String CodeObject_GetAttribute(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native boolean CodeObject_HasAttribute(long jarg1, CodeObject jarg1_, String jarg2);
  public final static native void CodeObject_SetAttribute(long jarg1, CodeObject jarg1_, String jarg2, String jarg3);
  public final static native long CodeObject_AttributesBegin(long jarg1, CodeObject jarg1_);
  public final static native long CodeObject_AttributesEnd(long jarg1, CodeObject jarg1_);
  public final static native void delete_CodeObjectsMapIterator(long jarg1);
  public final static native long new_CodeObjectsMapIterator(long jarg1, CodeObjectsMapIterator jarg1_);
  public final static native String CodeObjectsMapIterator_GetKey(long jarg1, CodeObjectsMapIterator jarg1_);
  public final static native long CodeObjectsMapIterator_GetValue(long jarg1, CodeObjectsMapIterator jarg1_);
  public final static native boolean CodeObjectsMapIterator_Equals(long jarg1, CodeObjectsMapIterator jarg1_, long jarg2, CodeObjectsMapIterator jarg2_);
  public final static native void CodeObjectsMapIterator_Advance(long jarg1, CodeObjectsMapIterator jarg1_);
  public final static native long new_CodeEngineResult__SWIG_0(boolean jarg1);
  public final static native long new_CodeEngineResult__SWIG_1();
  public final static native long new_CodeEngineResult__SWIG_2(long jarg1, CodeEngineResult jarg1_);
  public final static native void delete_CodeEngineResult(long jarg1);
  public final static native int CodeEngineResult_GetObjectCount(long jarg1, CodeEngineResult jarg1_);
  public final static native boolean CodeEngineResult_HasObject(long jarg1, CodeEngineResult jarg1_, String jarg2);
  public final static native long CodeEngineResult_GetCodeObject(long jarg1, CodeEngineResult jarg1_, String jarg2);
  public final static native void CodeEngineResult_SetCodeObject(long jarg1, CodeEngineResult jarg1_, String jarg2, long jarg3, CodeObject jarg3_);
  public final static native long CodeEngineResult_ObjectsBegin(long jarg1, CodeEngineResult jarg1_);
  public final static native long CodeEngineResult_ObjectsEnd(long jarg1, CodeEngineResult jarg1_);
  public final static native boolean CodeEngineResult_IsTerminal(long jarg1, CodeEngineResult jarg1_);
  public final static native void CodeEngineResult_SetTerminal__SWIG_0(long jarg1, CodeEngineResult jarg1_, boolean jarg2);
  public final static native void CodeEngineResult_SetTerminal__SWIG_1(long jarg1, CodeEngineResult jarg1_);
  public final static native void CodeEngineResult_Reset(long jarg1, CodeEngineResult jarg1_);
  public final static native void delete_CodeEngineSession(long jarg1);
  public final static native String CodeEngineSession_GetActivationRequest(long jarg1, CodeEngineSession jarg1_);
  public final static native void CodeEngineSession_Activate(long jarg1, CodeEngineSession jarg1_, String jarg2);
  public final static native boolean CodeEngineSession_IsActivated(long jarg1, CodeEngineSession jarg1_);
  public final static native long CodeEngineSession_Process(long jarg1, CodeEngineSession jarg1_, long jarg2, Image jarg2_);
  public final static native long CodeEngineSession_GetCurrentResult(long jarg1, CodeEngineSession jarg1_);
  public final static native boolean CodeEngineSession_IsResultTerminal(long jarg1, CodeEngineSession jarg1_);
  public final static native void CodeEngineSession_Reset(long jarg1, CodeEngineSession jarg1_);
  public final static native void delete_CodeEngineFeedbackContainer(long jarg1);
  public final static native long new_CodeEngineFeedbackContainer__SWIG_0();
  public final static native long new_CodeEngineFeedbackContainer__SWIG_1(long jarg1, CodeEngineFeedbackContainer jarg1_);
  public final static native int CodeEngineFeedbackContainer_GetQuadranglesCount(long jarg1, CodeEngineFeedbackContainer jarg1_);
  public final static native boolean CodeEngineFeedbackContainer_HasQuadrangle(long jarg1, CodeEngineFeedbackContainer jarg1_, String jarg2);
  public final static native long CodeEngineFeedbackContainer_GetQuadrangle(long jarg1, CodeEngineFeedbackContainer jarg1_, String jarg2);
  public final static native void CodeEngineFeedbackContainer_SetQuadrangle(long jarg1, CodeEngineFeedbackContainer jarg1_, String jarg2, long jarg3, Quadrangle jarg3_);
  public final static native void CodeEngineFeedbackContainer_RemoveQuadrangle(long jarg1, CodeEngineFeedbackContainer jarg1_, String jarg2);
  public final static native long CodeEngineFeedbackContainer_QuadranglesBegin(long jarg1, CodeEngineFeedbackContainer jarg1_);
  public final static native long CodeEngineFeedbackContainer_QuadranglesEnd(long jarg1, CodeEngineFeedbackContainer jarg1_);
  public final static native void delete_CodeEngineVisualizationFeedback(long jarg1);
  public final static native void CodeEngineVisualizationFeedback_FeedbackReceived(long jarg1, CodeEngineVisualizationFeedback jarg1_, long jarg2, CodeEngineFeedbackContainer jarg2_);
  public final static native long new_CodeEngineVisualizationFeedback();
  public final static native void CodeEngineVisualizationFeedback_director_connect(CodeEngineVisualizationFeedback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void CodeEngineVisualizationFeedback_change_ownership(CodeEngineVisualizationFeedback obj, long cptr, boolean take_or_release);
  public final static native void delete_CodeEngineWorkflowFeedback(long jarg1);
  public final static native void CodeEngineWorkflowFeedback_ResultReceived(long jarg1, CodeEngineWorkflowFeedback jarg1_, long jarg2, CodeEngineResult jarg2_);
  public final static native void CodeEngineWorkflowFeedback_SessionEnded(long jarg1, CodeEngineWorkflowFeedback jarg1_);
  public final static native long new_CodeEngineWorkflowFeedback();
  public final static native void CodeEngineWorkflowFeedback_director_connect(CodeEngineWorkflowFeedback obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void CodeEngineWorkflowFeedback_change_ownership(CodeEngineWorkflowFeedback obj, long cptr, boolean take_or_release);
  public final static native int CodeEngine_Barcode_get();
  public final static native int CodeEngine_CodeTextLine_get();
  public final static native int CodeEngine_MRZ_get();
  public final static native int CodeEngine_BankCard_get();
  public final static native int CodeEngine_PaymentDetails_get();
  public final static native int CodeEngine_LicensePlate_get();
  public final static native int CodeEngine_ShippingContainer_get();
  public final static native int EngineSettingsGroup_Global_get();
  public final static native int EngineSettingsGroup_Barcode_get();
  public final static native int EngineSettingsGroup_Card_get();
  public final static native int EngineSettingsGroup_CodeTextLine_get();
  public final static native int EngineSettingsGroup_Mrz_get();
  public final static native int EngineSettingsGroup_PaymentDetails_get();
  public final static native int EngineSettingsGroup_LicensePlate_get();
  public final static native int EngineSettingsGroup_ShippingContainer_get();
  public final static native int BarcodePreset_GS1_get();
  public final static native int BarcodePreset_AAMVA_get();
  public final static native int BarcodePreset_URL_get();
  public final static native int BarcodePreset_VCARD_get();
  public final static native int BarcodePreset_EMAIL_get();
  public final static native int BarcodePreset_ICALENDAR_get();
  public final static native int BarcodePreset_PHONE_get();
  public final static native int BarcodePreset_SMS_get();
  public final static native int BarcodePreset_ISBN_get();
  public final static native int BarcodePreset_WIFI_get();
  public final static native int BarcodePreset_GEO_get();
  public final static native int BarcodePreset_PAYMENT_get();
  public final static native int BarcodePreset_NONE_get();
  public final static native int engineSettingsGroupFromString(String jarg1);
  public final static native String toString(int jarg1);
  public final static native String presetToString(int jarg1);
  public final static native long CodeEngine_Create__SWIG_0(String jarg1, boolean jarg2);
  public final static native long CodeEngine_Create__SWIG_1(String jarg1);
  public final static native long CodeEngine_Create__SWIG_2(byte[] jarg1, boolean jarg3);
  public final static native long CodeEngine_Create__SWIG_3(byte[] jarg1);
  public final static native long CodeEngine_CreateFromEmbeddedBundle__SWIG_0(boolean jarg1);
  public final static native long CodeEngine_CreateFromEmbeddedBundle__SWIG_1();
  public final static native void delete_CodeEngine(long jarg1);
  public final static native String CodeEngine_GetVersion();
  public final static native long CodeEngine_GetDefaultSessionSettings(long jarg1, CodeEngine jarg1_);
  public final static native long CodeEngine_SpawnSession__SWIG_0(long jarg1, CodeEngine jarg1_, long jarg2, CodeEngineSessionSettings jarg2_, String jarg3, long jarg4, CodeEngineWorkflowFeedback jarg4_, long jarg5, CodeEngineVisualizationFeedback jarg5_);
  public final static native long CodeEngine_SpawnSession__SWIG_1(long jarg1, CodeEngine jarg1_, long jarg2, CodeEngineSessionSettings jarg2_, String jarg3, long jarg4, CodeEngineWorkflowFeedback jarg4_);
  public final static native long CodeEngine_SpawnSession__SWIG_2(long jarg1, CodeEngine jarg1_, long jarg2, CodeEngineSessionSettings jarg2_, String jarg3);
  public final static native boolean CodeEngine_IsEngineAvailable(long jarg1, CodeEngine jarg1_, int jarg2);

  public static void SwigDirector_CodeEngineVisualizationFeedback_FeedbackReceived(CodeEngineVisualizationFeedback jself, long feedback_container) {
    jself.FeedbackReceived(new CodeEngineFeedbackContainer(feedback_container, false));
  }
  public static void SwigDirector_CodeEngineWorkflowFeedback_ResultReceived(CodeEngineWorkflowFeedback jself, long result_received) {
    jself.ResultReceived(new CodeEngineResult(result_received, false));
  }
  public static void SwigDirector_CodeEngineWorkflowFeedback_SessionEnded(CodeEngineWorkflowFeedback jself) {
    jself.SessionEnded();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
