/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeObject obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeObject() {
    this(jnicodeengineJNI.new_CodeObject__SWIG_0(), true);
  }

  public CodeObject(String name, CodeObjectType object_type, boolean is_accepted, float confidence) {
    this(jnicodeengineJNI.new_CodeObject__SWIG_1(name, object_type.swigValue(), is_accepted, confidence), true);
  }

  public CodeObject(String name, CodeObjectType object_type, boolean is_accepted) {
    this(jnicodeengineJNI.new_CodeObject__SWIG_2(name, object_type.swigValue(), is_accepted), true);
  }

  public CodeObject(String name, CodeObjectType object_type) {
    this(jnicodeengineJNI.new_CodeObject__SWIG_3(name, object_type.swigValue()), true);
  }

  public CodeObject(CodeObject other) {
    this(jnicodeengineJNI.new_CodeObject__SWIG_4(CodeObject.getCPtr(other), other), true);
  }

  public int GetID() {
    return jnicodeengineJNI.CodeObject_GetID(swigCPtr, this);
  }

  public CodeObjectType GetType() {
    return CodeObjectType.swigToEnum(jnicodeengineJNI.CodeObject_GetType(swigCPtr, this));
  }

  public String GetTypeStr() {
    return jnicodeengineJNI.CodeObject_GetTypeStr(swigCPtr, this);
  }

  public String GetName() {
    return jnicodeengineJNI.CodeObject_GetName(swigCPtr, this);
  }

  public boolean IsAccepted() {
    return jnicodeengineJNI.CodeObject_IsAccepted(swigCPtr, this);
  }

  public boolean IsValidated() {
    return jnicodeengineJNI.CodeObject_IsValidated(swigCPtr, this);
  }

  public float GetConfidence() {
    return jnicodeengineJNI.CodeObject_GetConfidence(swigCPtr, this);
  }

  public void SetFirstDetectedFrame(int frame_number) {
    jnicodeengineJNI.CodeObject_SetFirstDetectedFrame(swigCPtr, this, frame_number);
  }

  public void SetLastUpdatedFrame(int frame_number) {
    jnicodeengineJNI.CodeObject_SetLastUpdatedFrame(swigCPtr, this, frame_number);
  }

  public int GetFirstDetectedFrame() {
    return jnicodeengineJNI.CodeObject_GetFirstDetectedFrame(swigCPtr, this);
  }

  public int GetLastUpdatedFrame() {
    return jnicodeengineJNI.CodeObject_GetLastUpdatedFrame(swigCPtr, this);
  }

  public boolean GetIsTerminal() {
    return jnicodeengineJNI.CodeObject_GetIsTerminal(swigCPtr, this);
  }

  public void SetIsTerminal(boolean is_terminal) {
    jnicodeengineJNI.CodeObject_SetIsTerminal(swigCPtr, this, is_terminal);
  }

  public boolean HasQuadrangle() {
    return jnicodeengineJNI.CodeObject_HasQuadrangle(swigCPtr, this);
  }

  public Quadrangle GetQuadrangle() {
    return new Quadrangle(jnicodeengineJNI.CodeObject_GetQuadrangle(swigCPtr, this), false);
  }

  public void SetQuadrangle(Quadrangle quad) {
    jnicodeengineJNI.CodeObject_SetQuadrangle(swigCPtr, this, Quadrangle.getCPtr(quad), quad);
  }

  public boolean HasImage() {
    return jnicodeengineJNI.CodeObject_HasImage(swigCPtr, this);
  }

  public Image GetImage() {
    return new Image(jnicodeengineJNI.CodeObject_GetImage(swigCPtr, this), false);
  }

  public void SetImage(Image img) {
    jnicodeengineJNI.CodeObject_SetImage(swigCPtr, this, Image.getCPtr(img), img);
  }

  public void RemoveImage() {
    jnicodeengineJNI.CodeObject_RemoveImage(swigCPtr, this);
  }

  public int GetComponentsCount() {
    return jnicodeengineJNI.CodeObject_GetComponentsCount(swigCPtr, this);
  }

  public Quadrangle GetComponent(String comp_name) {
    return new Quadrangle(jnicodeengineJNI.CodeObject_GetComponent(swigCPtr, this, comp_name), false);
  }

  public void SetComponent(String comp_name, Quadrangle comp) {
    jnicodeengineJNI.CodeObject_SetComponent(swigCPtr, this, comp_name, Quadrangle.getCPtr(comp), comp);
  }

  public boolean HasComponent(String comp_name) {
    return jnicodeengineJNI.CodeObject_HasComponent(swigCPtr, this, comp_name);
  }

  public QuadranglesMapIterator ComponentsBegin() {
    return new QuadranglesMapIterator(jnicodeengineJNI.CodeObject_ComponentsBegin(swigCPtr, this), true);
  }

  public QuadranglesMapIterator ComponentsEnd() {
    return new QuadranglesMapIterator(jnicodeengineJNI.CodeObject_ComponentsEnd(swigCPtr, this), true);
  }

  public int GetFieldsCount() {
    return jnicodeengineJNI.CodeObject_GetFieldsCount(swigCPtr, this);
  }

  public CodeField GetField(String field_name) {
    return new CodeField(jnicodeengineJNI.CodeObject_GetField(swigCPtr, this, field_name), false);
  }

  public void SetField(String field_name, CodeField code_field) {
    jnicodeengineJNI.CodeObject_SetField(swigCPtr, this, field_name, CodeField.getCPtr(code_field), code_field);
  }

  public boolean HasField(String field_name) {
    return jnicodeengineJNI.CodeObject_HasField(swigCPtr, this, field_name);
  }

  public void RemoveField(String field_name) {
    jnicodeengineJNI.CodeObject_RemoveField(swigCPtr, this, field_name);
  }

  public CodeFieldsMapIterator FieldsBegin() {
    return new CodeFieldsMapIterator(jnicodeengineJNI.CodeObject_FieldsBegin(swigCPtr, this), true);
  }

  public CodeFieldsMapIterator FieldsEnd() {
    return new CodeFieldsMapIterator(jnicodeengineJNI.CodeObject_FieldsEnd(swigCPtr, this), true);
  }

  public int GetAttributesCount() {
    return jnicodeengineJNI.CodeObject_GetAttributesCount(swigCPtr, this);
  }

  public String GetAttribute(String attr_name) {
    return jnicodeengineJNI.CodeObject_GetAttribute(swigCPtr, this, attr_name);
  }

  public boolean HasAttribute(String attr_name) {
    return jnicodeengineJNI.CodeObject_HasAttribute(swigCPtr, this, attr_name);
  }

  public void SetAttribute(String attr_name, String attr_value) {
    jnicodeengineJNI.CodeObject_SetAttribute(swigCPtr, this, attr_name, attr_value);
  }

  public StringsMapIterator AttributesBegin() {
    return new StringsMapIterator(jnicodeengineJNI.CodeObject_AttributesBegin(swigCPtr, this), true);
  }

  public StringsMapIterator AttributesEnd() {
    return new StringsMapIterator(jnicodeengineJNI.CodeObject_AttributesEnd(swigCPtr, this), true);
  }

}
