/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

public final class CodeEngineType {
  public final static CodeEngineType CodeEngine_Barcode = new CodeEngineType("CodeEngine_Barcode", jnicodeengineJNI.CodeEngine_Barcode_get());
  public final static CodeEngineType CodeEngine_CodeTextLine = new CodeEngineType("CodeEngine_CodeTextLine", jnicodeengineJNI.CodeEngine_CodeTextLine_get());
  public final static CodeEngineType CodeEngine_MRZ = new CodeEngineType("CodeEngine_MRZ", jnicodeengineJNI.CodeEngine_MRZ_get());
  public final static CodeEngineType CodeEngine_BankCard = new CodeEngineType("CodeEngine_BankCard", jnicodeengineJNI.CodeEngine_BankCard_get());
  public final static CodeEngineType CodeEngine_PaymentDetails = new CodeEngineType("CodeEngine_PaymentDetails", jnicodeengineJNI.CodeEngine_PaymentDetails_get());
  public final static CodeEngineType CodeEngine_LicensePlate = new CodeEngineType("CodeEngine_LicensePlate", jnicodeengineJNI.CodeEngine_LicensePlate_get());
  public final static CodeEngineType CodeEngine_ShippingContainer = new CodeEngineType("CodeEngine_ShippingContainer", jnicodeengineJNI.CodeEngine_ShippingContainer_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CodeEngineType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CodeEngineType.class + " with value " + swigValue);
  }

  private CodeEngineType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CodeEngineType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CodeEngineType(String swigName, CodeEngineType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CodeEngineType[] swigValues = { CodeEngine_Barcode, CodeEngine_CodeTextLine, CodeEngine_MRZ, CodeEngine_BankCard, CodeEngine_PaymentDetails, CodeEngine_LicensePlate, CodeEngine_ShippingContainer };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

