//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

public enum CodeEngineType {
  CodeEngine_Barcode = (1 << 1),
  CodeEngine_CodeTextLine = (1 << 2),
  CodeEngine_MRZ = (1 << 3),
  CodeEngine_BankCard = (1 << 4),
  CodeEngine_PaymentDetails = (1 << 5),
  CodeEngine_LicensePlate = (1 << 6),
  CodeEngine_ShippingContainer = (1 << 7)
}

}
