//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

  using se.common;

class cscodeenginePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="SWIGRegisterExceptionCallbacks_cscodeengine")]
    public static extern void SWIGRegisterExceptionCallbacks_cscodeengine(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_cscodeengine")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_cscodeengine(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_cscodeengine(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_cscodeengine(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="SWIGRegisterStringCallback_cscodeengine")]
    public static extern void SWIGRegisterStringCallback_cscodeengine(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_cscodeengine(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static cscodeenginePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Clear___")]
  public static extern void Utf16CharVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Add___")]
  public static extern void Utf16CharVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_size___")]
  public static extern uint Utf16CharVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_capacity___")]
  public static extern uint Utf16CharVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_reserve___")]
  public static extern void Utf16CharVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_Utf16CharVector__SWIG_0___")]
  public static extern global::System.IntPtr new_Utf16CharVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_Utf16CharVector__SWIG_1___")]
  public static extern global::System.IntPtr new_Utf16CharVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_Utf16CharVector__SWIG_2___")]
  public static extern global::System.IntPtr new_Utf16CharVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_getitemcopy___")]
  public static extern ushort Utf16CharVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_getitem___")]
  public static extern ushort Utf16CharVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_setitem___")]
  public static extern void Utf16CharVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_AddRange___")]
  public static extern void Utf16CharVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_GetRange___")]
  public static extern global::System.IntPtr Utf16CharVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Insert___")]
  public static extern void Utf16CharVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_InsertRange___")]
  public static extern void Utf16CharVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_RemoveAt___")]
  public static extern void Utf16CharVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_RemoveRange___")]
  public static extern void Utf16CharVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Repeat___")]
  public static extern global::System.IntPtr Utf16CharVector_Repeat(ushort jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Reverse__SWIG_0___")]
  public static extern void Utf16CharVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Reverse__SWIG_1___")]
  public static extern void Utf16CharVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_SetRange___")]
  public static extern void Utf16CharVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Contains___")]
  public static extern bool Utf16CharVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_IndexOf___")]
  public static extern int Utf16CharVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_LastIndexOf___")]
  public static extern int Utf16CharVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_Utf16CharVector_Remove___")]
  public static extern bool Utf16CharVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_Utf16CharVector___")]
  public static extern void delete_Utf16CharVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Clear___")]
  public static extern void StringVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Add___")]
  public static extern void StringVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_size___")]
  public static extern uint StringVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_capacity___")]
  public static extern uint StringVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_reserve___")]
  public static extern void StringVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_StringVector__SWIG_0___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_StringVector__SWIG_1___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_StringVector__SWIG_2___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_getitemcopy___")]
  public static extern string StringVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_getitem___")]
  public static extern string StringVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_setitem___")]
  public static extern void StringVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_AddRange___")]
  public static extern void StringVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_GetRange___")]
  public static extern global::System.IntPtr StringVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Insert___")]
  public static extern void StringVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_InsertRange___")]
  public static extern void StringVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_RemoveAt___")]
  public static extern void StringVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_RemoveRange___")]
  public static extern void StringVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Repeat___")]
  public static extern global::System.IntPtr StringVector_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Reverse__SWIG_0___")]
  public static extern void StringVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Reverse__SWIG_1___")]
  public static extern void StringVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_SetRange___")]
  public static extern void StringVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Contains___")]
  public static extern bool StringVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_IndexOf___")]
  public static extern int StringVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_LastIndexOf___")]
  public static extern int StringVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector_Remove___")]
  public static extern bool StringVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_StringVector___")]
  public static extern void delete_StringVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_Clear___")]
  public static extern void StringVector2d_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_Add___")]
  public static extern void StringVector2d_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_size___")]
  public static extern uint StringVector2d_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_capacity___")]
  public static extern uint StringVector2d_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_reserve___")]
  public static extern void StringVector2d_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_StringVector2d__SWIG_0___")]
  public static extern global::System.IntPtr new_StringVector2d__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_StringVector2d__SWIG_1___")]
  public static extern global::System.IntPtr new_StringVector2d__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_StringVector2d__SWIG_2___")]
  public static extern global::System.IntPtr new_StringVector2d__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_getitemcopy___")]
  public static extern global::System.IntPtr StringVector2d_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_getitem___")]
  public static extern global::System.IntPtr StringVector2d_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_setitem___")]
  public static extern void StringVector2d_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_AddRange___")]
  public static extern void StringVector2d_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_GetRange___")]
  public static extern global::System.IntPtr StringVector2d_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_Insert___")]
  public static extern void StringVector2d_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_InsertRange___")]
  public static extern void StringVector2d_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_RemoveAt___")]
  public static extern void StringVector2d_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_RemoveRange___")]
  public static extern void StringVector2d_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_Repeat___")]
  public static extern global::System.IntPtr StringVector2d_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_Reverse__SWIG_0___")]
  public static extern void StringVector2d_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_Reverse__SWIG_1___")]
  public static extern void StringVector2d_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_StringVector2d_SetRange___")]
  public static extern void StringVector2d_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_StringVector2d___")]
  public static extern void delete_StringVector2d(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngineSessionSettings___")]
  public static extern void delete_CodeEngineSessionSettings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSessionSettings_Clone___")]
  public static extern global::System.IntPtr CodeEngineSessionSettings_Clone(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSessionSettings_GetOption___")]
  public static extern string CodeEngineSessionSettings_GetOption(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSessionSettings_SettingsBegin___")]
  public static extern global::System.IntPtr CodeEngineSessionSettings_SettingsBegin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSessionSettings_SettingsEnd___")]
  public static extern global::System.IntPtr CodeEngineSessionSettings_SettingsEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSessionSettings_HasOption___")]
  public static extern bool CodeEngineSessionSettings_HasOption(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSessionSettings_SetOption___")]
  public static extern void CodeEngineSessionSettings_SetOption(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_0___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_1___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_1(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_2___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_2(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_3___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_3(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_4___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_4(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_5___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_5(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_6___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_6(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeField___")]
  public static extern void delete_CodeField(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeField__SWIG_7___")]
  public static extern global::System.IntPtr new_CodeField__SWIG_7(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_Name___")]
  public static extern string CodeField_Name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_SetName___")]
  public static extern void CodeField_SetName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_IsAccepted___")]
  public static extern bool CodeField_IsAccepted(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_SetIsAccepted___")]
  public static extern void CodeField_SetIsAccepted(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_GetConfidence___")]
  public static extern double CodeField_GetConfidence(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_SetConfidence___")]
  public static extern void CodeField_SetConfidence(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_IsTerminal___")]
  public static extern bool CodeField_IsTerminal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_SetIsTerminal___")]
  public static extern void CodeField_SetIsTerminal(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_HasBinaryRepresentation___")]
  public static extern bool CodeField_HasBinaryRepresentation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_GetBinaryRepresentation___")]
  public static extern global::System.IntPtr CodeField_GetBinaryRepresentation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_SetBinaryRepresentation___")]
  public static extern void CodeField_SetBinaryRepresentation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_HasOcrStringRepresentation___")]
  public static extern bool CodeField_HasOcrStringRepresentation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_GetOcrString___")]
  public static extern global::System.IntPtr CodeField_GetOcrString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeField_SetOcrStringRepresentation___")]
  public static extern void CodeField_SetOcrStringRepresentation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeFieldsMapIterator___")]
  public static extern void delete_CodeFieldsMapIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeFieldsMapIterator___")]
  public static extern global::System.IntPtr new_CodeFieldsMapIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeFieldsMapIterator_GetKey___")]
  public static extern string CodeFieldsMapIterator_GetKey(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeFieldsMapIterator_GetValue___")]
  public static extern global::System.IntPtr CodeFieldsMapIterator_GetValue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeFieldsMapIterator_Equals___")]
  public static extern bool CodeFieldsMapIterator_Equals(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeFieldsMapIterator_Advance___")]
  public static extern void CodeFieldsMapIterator_Advance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeObject__SWIG_0___")]
  public static extern global::System.IntPtr new_CodeObject__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeObject__SWIG_1___")]
  public static extern global::System.IntPtr new_CodeObject__SWIG_1(string jarg1, int jarg2, bool jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeObject__SWIG_2___")]
  public static extern global::System.IntPtr new_CodeObject__SWIG_2(string jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeObject__SWIG_3___")]
  public static extern global::System.IntPtr new_CodeObject__SWIG_3(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeObject__SWIG_4___")]
  public static extern global::System.IntPtr new_CodeObject__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeObject___")]
  public static extern void delete_CodeObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetID___")]
  public static extern int CodeObject_GetID(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetType___")]
  public static extern int CodeObject_GetType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetTypeStr___")]
  public static extern string CodeObject_GetTypeStr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetName___")]
  public static extern string CodeObject_GetName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_IsAccepted___")]
  public static extern bool CodeObject_IsAccepted(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_IsValidated___")]
  public static extern bool CodeObject_IsValidated(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetConfidence___")]
  public static extern float CodeObject_GetConfidence(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetFirstDetectedFrame___")]
  public static extern void CodeObject_SetFirstDetectedFrame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetLastUpdatedFrame___")]
  public static extern void CodeObject_SetLastUpdatedFrame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetFirstDetectedFrame___")]
  public static extern int CodeObject_GetFirstDetectedFrame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetLastUpdatedFrame___")]
  public static extern int CodeObject_GetLastUpdatedFrame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetIsTerminal___")]
  public static extern bool CodeObject_GetIsTerminal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetIsTerminal___")]
  public static extern void CodeObject_SetIsTerminal(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_HasQuadrangle___")]
  public static extern bool CodeObject_HasQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetQuadrangle___")]
  public static extern global::System.IntPtr CodeObject_GetQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetQuadrangle___")]
  public static extern void CodeObject_SetQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_HasImage___")]
  public static extern bool CodeObject_HasImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetImage___")]
  public static extern global::System.IntPtr CodeObject_GetImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetImage___")]
  public static extern void CodeObject_SetImage(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_RemoveImage___")]
  public static extern void CodeObject_RemoveImage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetComponentsCount___")]
  public static extern int CodeObject_GetComponentsCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetComponent___")]
  public static extern global::System.IntPtr CodeObject_GetComponent(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetComponent___")]
  public static extern void CodeObject_SetComponent(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_HasComponent___")]
  public static extern bool CodeObject_HasComponent(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_ComponentsBegin___")]
  public static extern global::System.IntPtr CodeObject_ComponentsBegin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_ComponentsEnd___")]
  public static extern global::System.IntPtr CodeObject_ComponentsEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetFieldsCount___")]
  public static extern int CodeObject_GetFieldsCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetField___")]
  public static extern global::System.IntPtr CodeObject_GetField(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetField___")]
  public static extern void CodeObject_SetField(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_HasField___")]
  public static extern bool CodeObject_HasField(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_RemoveField___")]
  public static extern void CodeObject_RemoveField(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_FieldsBegin___")]
  public static extern global::System.IntPtr CodeObject_FieldsBegin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_FieldsEnd___")]
  public static extern global::System.IntPtr CodeObject_FieldsEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetAttributesCount___")]
  public static extern int CodeObject_GetAttributesCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_GetAttribute___")]
  public static extern string CodeObject_GetAttribute(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_HasAttribute___")]
  public static extern bool CodeObject_HasAttribute(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_SetAttribute___")]
  public static extern void CodeObject_SetAttribute(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_AttributesBegin___")]
  public static extern global::System.IntPtr CodeObject_AttributesBegin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObject_AttributesEnd___")]
  public static extern global::System.IntPtr CodeObject_AttributesEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeObjectsMapIterator___")]
  public static extern void delete_CodeObjectsMapIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeObjectsMapIterator___")]
  public static extern global::System.IntPtr new_CodeObjectsMapIterator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObjectsMapIterator_GetKey___")]
  public static extern string CodeObjectsMapIterator_GetKey(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObjectsMapIterator_GetValue___")]
  public static extern global::System.IntPtr CodeObjectsMapIterator_GetValue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObjectsMapIterator_Equals___")]
  public static extern bool CodeObjectsMapIterator_Equals(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeObjectsMapIterator_Advance___")]
  public static extern void CodeObjectsMapIterator_Advance(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineResult__SWIG_0___")]
  public static extern global::System.IntPtr new_CodeEngineResult__SWIG_0(bool jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineResult__SWIG_1___")]
  public static extern global::System.IntPtr new_CodeEngineResult__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineResult__SWIG_2___")]
  public static extern global::System.IntPtr new_CodeEngineResult__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngineResult___")]
  public static extern void delete_CodeEngineResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_GetObjectCount___")]
  public static extern int CodeEngineResult_GetObjectCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_HasObject___")]
  public static extern bool CodeEngineResult_HasObject(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_GetCodeObject___")]
  public static extern global::System.IntPtr CodeEngineResult_GetCodeObject(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_SetCodeObject___")]
  public static extern void CodeEngineResult_SetCodeObject(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_ObjectsBegin___")]
  public static extern global::System.IntPtr CodeEngineResult_ObjectsBegin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_ObjectsEnd___")]
  public static extern global::System.IntPtr CodeEngineResult_ObjectsEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_IsTerminal___")]
  public static extern bool CodeEngineResult_IsTerminal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_SetTerminal__SWIG_0___")]
  public static extern void CodeEngineResult_SetTerminal__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_SetTerminal__SWIG_1___")]
  public static extern void CodeEngineResult_SetTerminal__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineResult_Reset___")]
  public static extern void CodeEngineResult_Reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngineSession___")]
  public static extern void delete_CodeEngineSession(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_GetActivationRequest___")]
  public static extern string CodeEngineSession_GetActivationRequest(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_Activate___")]
  public static extern void CodeEngineSession_Activate(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_IsActivated___")]
  public static extern bool CodeEngineSession_IsActivated(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_Process___")]
  public static extern global::System.IntPtr CodeEngineSession_Process(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_GetCurrentResult___")]
  public static extern global::System.IntPtr CodeEngineSession_GetCurrentResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_IsResultTerminal___")]
  public static extern bool CodeEngineSession_IsResultTerminal(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineSession_Reset___")]
  public static extern void CodeEngineSession_Reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngineFeedbackContainer___")]
  public static extern void delete_CodeEngineFeedbackContainer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineFeedbackContainer__SWIG_0___")]
  public static extern global::System.IntPtr new_CodeEngineFeedbackContainer__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineFeedbackContainer__SWIG_1___")]
  public static extern global::System.IntPtr new_CodeEngineFeedbackContainer__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_GetQuadranglesCount___")]
  public static extern int CodeEngineFeedbackContainer_GetQuadranglesCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_HasQuadrangle___")]
  public static extern bool CodeEngineFeedbackContainer_HasQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_GetQuadrangle___")]
  public static extern global::System.IntPtr CodeEngineFeedbackContainer_GetQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_SetQuadrangle___")]
  public static extern void CodeEngineFeedbackContainer_SetQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_RemoveQuadrangle___")]
  public static extern void CodeEngineFeedbackContainer_RemoveQuadrangle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_QuadranglesBegin___")]
  public static extern global::System.IntPtr CodeEngineFeedbackContainer_QuadranglesBegin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineFeedbackContainer_QuadranglesEnd___")]
  public static extern global::System.IntPtr CodeEngineFeedbackContainer_QuadranglesEnd(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngineVisualizationFeedback___")]
  public static extern void delete_CodeEngineVisualizationFeedback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineVisualizationFeedback_FeedbackReceived___")]
  public static extern void CodeEngineVisualizationFeedback_FeedbackReceived(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineVisualizationFeedback___")]
  public static extern global::System.IntPtr new_CodeEngineVisualizationFeedback();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineVisualizationFeedback_director_connect___")]
  public static extern void CodeEngineVisualizationFeedback_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, CodeEngineVisualizationFeedback.SwigDelegateCodeEngineVisualizationFeedback_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngineWorkflowFeedback___")]
  public static extern void delete_CodeEngineWorkflowFeedback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineWorkflowFeedback_ResultReceived___")]
  public static extern void CodeEngineWorkflowFeedback_ResultReceived(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineWorkflowFeedback_SessionEnded___")]
  public static extern void CodeEngineWorkflowFeedback_SessionEnded(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_new_CodeEngineWorkflowFeedback___")]
  public static extern global::System.IntPtr new_CodeEngineWorkflowFeedback();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngineWorkflowFeedback_director_connect___")]
  public static extern void CodeEngineWorkflowFeedback_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, CodeEngineWorkflowFeedback.SwigDelegateCodeEngineWorkflowFeedback_0 delegate0, CodeEngineWorkflowFeedback.SwigDelegateCodeEngineWorkflowFeedback_1 delegate1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_engineSettingsGroupFromString___")]
  public static extern int engineSettingsGroupFromString(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_toString___")]
  public static extern string toString(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_presetToString___")]
  public static extern string presetToString(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_Create__SWIG_0___")]
  public static extern global::System.IntPtr CodeEngine_Create__SWIG_0(string jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_Create__SWIG_1___")]
  public static extern global::System.IntPtr CodeEngine_Create__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_Create__SWIG_2___")]
  public static extern global::System.IntPtr CodeEngine_Create__SWIG_2([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_Create__SWIG_3___")]
  public static extern global::System.IntPtr CodeEngine_Create__SWIG_3([global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_CreateFromEmbeddedBundle__SWIG_0___")]
  public static extern global::System.IntPtr CodeEngine_CreateFromEmbeddedBundle__SWIG_0(bool jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_CreateFromEmbeddedBundle__SWIG_1___")]
  public static extern global::System.IntPtr CodeEngine_CreateFromEmbeddedBundle__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_delete_CodeEngine___")]
  public static extern void delete_CodeEngine(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_GetVersion___")]
  public static extern string CodeEngine_GetVersion();

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_GetDefaultSessionSettings___")]
  public static extern global::System.IntPtr CodeEngine_GetDefaultSessionSettings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_SpawnSession__SWIG_0___")]
  public static extern global::System.IntPtr CodeEngine_SpawnSession__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_SpawnSession__SWIG_1___")]
  public static extern global::System.IntPtr CodeEngine_SpawnSession__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_SpawnSession__SWIG_2___")]
  public static extern global::System.IntPtr CodeEngine_SpawnSession__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("cscodeengine", EntryPoint="CSharp_sefcode_CodeEngine_IsEngineAvailable___")]
  public static extern bool CodeEngine_IsEngineAvailable(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);
}

}
