//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.code {

public enum EngineSettingsGroup {
  Global = 1 << 1,
  Barcode = 1 << 2,
  Card = 1 << 3,
  CodeTextLine = 1 << 4,
  Mrz = 1 << 5,
  PaymentDetails = 1 << 6,
  LicensePlate = 1 << 7,
  ShippingContainer = 1 << 8
}

}
