/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeEngineResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeEngineResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeEngineResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeEngineResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeEngineResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeEngineResult(boolean is_terminal) {
    this(jnicodeengineJNI.new_CodeEngineResult__SWIG_0(is_terminal), true);
  }

  public CodeEngineResult() {
    this(jnicodeengineJNI.new_CodeEngineResult__SWIG_1(), true);
  }

  public CodeEngineResult(CodeEngineResult other) {
    this(jnicodeengineJNI.new_CodeEngineResult__SWIG_2(CodeEngineResult.getCPtr(other), other), true);
  }

  public int GetObjectCount() {
    return jnicodeengineJNI.CodeEngineResult_GetObjectCount(swigCPtr, this);
  }

  public boolean HasObject(String object_name) {
    return jnicodeengineJNI.CodeEngineResult_HasObject(swigCPtr, this, object_name);
  }

  public CodeObject GetCodeObject(String object_name) {
    return new CodeObject(jnicodeengineJNI.CodeEngineResult_GetCodeObject(swigCPtr, this, object_name), false);
  }

  public void SetCodeObject(String object_name, CodeObject code_object) {
    jnicodeengineJNI.CodeEngineResult_SetCodeObject(swigCPtr, this, object_name, CodeObject.getCPtr(code_object), code_object);
  }

  public CodeObjectsMapIterator ObjectsBegin() {
    return new CodeObjectsMapIterator(jnicodeengineJNI.CodeEngineResult_ObjectsBegin(swigCPtr, this), true);
  }

  public CodeObjectsMapIterator ObjectsEnd() {
    return new CodeObjectsMapIterator(jnicodeengineJNI.CodeEngineResult_ObjectsEnd(swigCPtr, this), true);
  }

  public boolean IsTerminal() {
    return jnicodeengineJNI.CodeEngineResult_IsTerminal(swigCPtr, this);
  }

  public void SetTerminal(boolean terminal) {
    jnicodeengineJNI.CodeEngineResult_SetTerminal__SWIG_0(swigCPtr, this, terminal);
  }

  public void SetTerminal() {
    jnicodeengineJNI.CodeEngineResult_SetTerminal__SWIG_1(swigCPtr, this);
  }

  public void Reset() {
    jnicodeengineJNI.CodeEngineResult_Reset(swigCPtr, this);
  }

}
