/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.code;

import com.smartengines.common.*;

public class CodeFieldsMapIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public CodeFieldsMapIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CodeFieldsMapIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(CodeFieldsMapIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnicodeengineJNI.delete_CodeFieldsMapIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CodeFieldsMapIterator(CodeFieldsMapIterator other) {
    this(jnicodeengineJNI.new_CodeFieldsMapIterator(CodeFieldsMapIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jnicodeengineJNI.CodeFieldsMapIterator_GetKey(swigCPtr, this);
  }

  public CodeField GetValue() {
    return new CodeField(jnicodeengineJNI.CodeFieldsMapIterator_GetValue(swigCPtr, this), false);
  }

  public boolean Equals(CodeFieldsMapIterator rvalue) {
    return jnicodeengineJNI.CodeFieldsMapIterator_Equals(swigCPtr, this, CodeFieldsMapIterator.getCPtr(rvalue), rvalue);
  }

  public void Advance() {
    jnicodeengineJNI.CodeFieldsMapIterator_Advance(swigCPtr, this);
  }

}
